/**
 * Internationalization (i18n) Module
 *
 * Translations for 30+ languages with regional variant support
 * RTL support for Arabic and Hebrew
 *
 * Note: Translations generated by AI - native speaker review recommended
 */

// RTL languages
const RTL_LANGUAGES = new Set(['ar', 'he', 'ur', 'yi']);

// Locale fallback map: specific locale → fallback chain
// Keys use proper BCP 47 casing: language-Script-REGION
const LOCALE_FALLBACK = {
    // German variants
    'de-AT': 'de', 'de-CH': 'de', 'de-BE': 'de', 'de-LI': 'de',
    // English variants
    'en-GB': 'en', 'en-US': 'en', 'en-AU': 'en', 'en-NZ': 'en', 'en-CA': 'en', 'en-IN': 'en', 'en-ZA': 'en',
    // Spanish variants
    'es-MX': 'es', 'es-AR': 'es', 'es-CO': 'es', 'es-CL': 'es', 'es-PE': 'es', 'es-VE': 'es',
    // Portuguese variants
    'pt-BR': 'pt', 'pt-PT': 'pt',
    // French variants
    'fr-CA': 'fr', 'fr-BE': 'fr', 'fr-CH': 'fr',
    // Chinese variants
    'zh': 'zh-Hans',  // Plain 'zh' defaults to Simplified Chinese
    'zh-CN': 'zh-Hans', 'zh-SG': 'zh-Hans', 'zh-Hans-CN': 'zh-Hans', 'zh-Hans-SG': 'zh-Hans',
    'zh-TW': 'zh-Hant', 'zh-HK': 'zh-Hant', 'zh-MO': 'zh-Hant', 'zh-Hant-TW': 'zh-Hant', 'zh-Hant-HK': 'zh-Hant',
    // Arabic variants
    'ar-EG': 'ar', 'ar-SA': 'ar', 'ar-MA': 'ar', 'ar-DZ': 'ar', 'ar-TN': 'ar', 'ar-SY': 'ar', 'ar-IQ': 'ar',
    // Swedish variants
    'sv-SE': 'sv', 'sv-FI': 'sv',
    // Norwegian variants
    'nb-NO': 'nb', 'nn-NO': 'nn', 'no-NO': 'nb',
    // Polish variants
    'pl-PL': 'pl', 'pl-US': 'pl',
    // Urdu variants
    'ur-PK': 'ur', 'ur-IN': 'ur',
    // Punjabi variants
    'pa-IN': 'pa', 'pa-PK': 'pa',
    // Indonesian variants
    'id-ID': 'id',
    // Tagalog/Filipino variants
    'tl-PH': 'tl', 'fil-PH': 'tl', 'fil': 'tl',  // Android uses 'fil' but we have 'tl' translation
    // Vietnamese variants
    'vi-VN': 'vi',
    // Thai variants
    'th-TH': 'th',
    // Azerbaijani variants
    'az-AZ': 'az',
    // Uzbek variants
    'uz-UZ': 'uz',
    // Kazakh variants
    'kk-KZ': 'kk',
    // Georgian variants
    'ka-GE': 'ka',
    // Armenian variants
    'hy-AM': 'hy',
    // Belarusian variants
    'be-BY': 'be',
    // Mongolian variants
    'mn-MN': 'mn',
    'mn-Mong-MN': 'mn-Mong', 'mn-Mong-CN': 'mn-Mong',
    // Note: Plain 'mn-Mong' without region is handled by exact TRANSLATIONS match
    // Amharic variants
    'am-ET': 'am',
    // Sinhala variants
    'si-LK': 'si',
    // Bosnian variants
    'bs-BA': 'bs',
    // Macedonian variants
    'mk-MK': 'mk',
    // Croatian variants
    'hr-HR': 'hr', 'hr-BA': 'hr',
    // Serbian variants - Cyrillic (default)
    'sr': 'sr-Cyrl', 'sr-RS': 'sr-Cyrl', 'sr-BA': 'sr-Cyrl', 'sr-ME': 'sr-Cyrl',
    'sr-Cyrl-RS': 'sr-Cyrl', 'sr-Cyrl-BA': 'sr-Cyrl', 'sr-Cyrl-ME': 'sr-Cyrl',
    // Serbian variants - Latin
    'sr-Latn-RS': 'sr-Latn', 'sr-Latn-BA': 'sr-Latn', 'sr-Latn-ME': 'sr-Latn',
    // Serbo-Croatian (deprecated BCP 47 code, but still reported by browsers)
    'sh': 'sr-Latn',
    // Catalan variants
    'ca-ES': 'ca', 'ca-AD': 'ca',
    // Basque variants
    'eu-ES': 'eu',
    // Tibetan variants
    'bo-CN': 'bo', 'bo-IN': 'bo',
    // Joke locales
    'en-FE': 'en-FE',
    'cs-FE': 'cs-FE',
    'sk-FE': 'sk-FE',
    '67': '67',
};

const TRANSLATIONS = {
    // English (default)
    en: {
        title: "PDF Monochrome G4 Compressor",
        subtitle: "Compress PDFs by reducing colors to bilevel monochrome, by reducing DPI resolution, and by using the efficient CCITT Group 4 compression inside PDF, also known as ITU-T T.6 or MMR or Fax compression.",
        privacyNotice: "🔒 Works 100% offline. Your PDFs never leave your device.",
        chooseFile: "Choose PDF File",
        conversionMode: "Conversion Mode:",
        noDither: "Non-dithered (Sharp)",
        dither: "Dithered (Smooth)",
        ditherSelected: "Dither only selected pages",
        pageRangePlaceholder: "e.g., 1, 3-5, 8, 10-12",
        pageRangeHint: "Enter page numbers and ranges separated by commas",
        pageSize: "Page Size:",
        pageSizeA4Portrait: "A4 Portrait",
        pageSizeA4Landscape: "A4 Landscape",
        pageSizeLetterPortrait: "Letter Portrait",
        pageSizeLetterLandscape: "Letter Landscape",
        pageSizeLegalPortrait: "US Legal Portrait",
        outputDpi: "Output DPI (Resolution):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Custom DPI",
        dpiHint: "Higher DPI = larger file size but better quality. 310 DPI recommended.",
        compressButton: "Compress",
        processing: "Processing...",
        credits: "Built with PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Licensed under Apache 2.0 • View Licenses & Attributions",
        about: "About This Project • A Study in Questionable Decisions",
        lowQualityWarning: "Warning: Low DPI may result in poor quality output. Text may be difficult to read and fine details may be lost.",
        resultSaveButton: "Save the result PDF",
        resultRecommendIgnore: "For this particular PDF, we recommend using your original PDF and ignoring this app.",
        resultDidntCompressWell: " The PDF didn't compress well.",
        resultBecameBigger: " The PDF became bigger.",
        resultAppPurpose: "This app is best used with scanned documents with high-contrast black and white look (you have to use another app for the scanning). If the PDF was already optimized well, this app can't help. This app exists only because most available PDF scanner apps save the nicely-looking result with inefficient JPEG compression instead of the efficient CCITT G4 compression.",
        resultDitheringNote: "Dithering makes the compression worse but is sometimes necessary for graphics or low-contrast text.",
        resultDitheringAdvice: " Consider not using dithering, or using dithering only with selected pages, e.g. where some graphics are. Text is usually best without dithering.",
        advancedTricks: "Advanced technological tricks",
        useJBIG2Label: "Use lossy JBIG2 compression instead of CCITT G4",
        jbig2Warning: "⚠️ Improve compression by using JBIG2 compression instead of CCITT G4 compression. Small similar characters might be confused (e.g. 6 with 8). Old devices might be unable to open the PDF.",
        preserveRotationLabel: "Try to preserve page rotation",
        metadataSection: "Metadata",
        includeTimestampLabel: "Include Created & Modified timestamps",
        ramWarningHigh: "Note: The combination of page count and DPI resolution for this file results in high estimated resource usage ({ram}). Processing may be slow and produce large output files.",
        ramWarningCritical: "Warning: The combination of page count and DPI resolution for this file results in very high estimated resource usage ({ram}). Your device may become hot, run slowly, or run out of memory. This is typically only recommended for short documents or when converting PDFs to a barebones format to work around printing issues.",
        jbig2DisabledMpix: "JBIG2 is disabled: the total image data ({mpix} megapixels, from page size × DPI × {pages} pages) exceeds the 475 megapixel limit of the JBIG2 encoder. Lower the DPI or use fewer pages to enable JBIG2.",
        jbig2DisabledPages: "JBIG2 is disabled: this PDF has {pages} pages, exceeding the 120-page limit of the JBIG2 encoder. The encoder's symbol dictionary cannot handle more than 120 pages reliably.",
        ramOverrideAcceptRisk: " (my device can run out of memory or run hot, the application might crash, and I accept that risk, just let me click the Compress button)",
        fileInfoPageCount: "Page count: {pages}",
        fileInfoFileSize: "File size: {size}",
        inputHint: "This app is designed for PDFs containing scans of paper documents that you want to convert to black-and-white and make the file size smaller. If your PDF contains copiable text (e.g. exports from office applications, digital books, exported web pages), it is probably already well optimized and this app likely won't produce good results. Similarly, if your scanned PDF was already compressed with CCITT G4, JBIG2, or MRC compression, re-compressing it here will likely cause generation loss (quality degradation from re-encoding) without meaningful size reduction. For best results, always compress the original un-optimized scan.",
    },

    // German
    de: {
        title: "PDF Monochrom G4 Kompressor",
        subtitle: "PDFs komprimieren durch Reduzierung auf Schwarzweiß, Anpassung der DPI-Auflösung und Verwendung der effizienten CCITT Group 4 Kompression (ITU-T T.6, MMR oder Fax-Kompression).",        privacyNotice: "🔒 Funktioniert 100% offline. Ihre PDFs verlassen niemals Ihr Gerät.",
        chooseFile: "PDF-Datei wählen",
        conversionMode: "Konvertierungsmodus:",
        noDither: "Ohne Dithering (Scharf)",
        dither: "Mit Dithering (Weich)",
        ditherSelected: "Nur ausgewählte Seiten mit Dithering",
        pageRangePlaceholder: "z.B. 1, 3-5, 8, 10-12",
        pageRangeHint: "Seitenzahlen und Bereiche durch Kommas getrennt eingeben",
        pageSize: "Seitengröße:",
        pageSizeA4Portrait: "A4 Hochformat",
        pageSizeA4Landscape: "A4 Querformat",
        pageSizeLetterPortrait: "Letter Hochformat",
        pageSizeLetterLandscape: "Letter Querformat",
        pageSizeLegalPortrait: "US Legal Hochformat",
        outputDpi: "Ausgabe-DPI (Auflösung):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Benutzerdefiniert",
        dpiHint: "Höhere DPI = größere Datei, aber bessere Qualität. 310 DPI empfohlen.",
        compressButton: "Komprimieren",
        processing: "Verarbeitung läuft...",
        credits: "Erstellt mit PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Lizenziert unter Apache 2.0 • Lizenzen & Zuordnungen ansehen",
        about: "Über dieses Projekt • Eine Studie fragwürdiger Entscheidungen",        lowQualityWarning: "Warnung: Niedrige DPI können zu schlechter Qualität führen. Text kann schwer lesbar sein und feine Details können verloren gehen.",
        resultSaveButton: "Ergebnis-PDF speichern",
        resultRecommendIgnore: "Für diese spezielle PDF empfehlen wir, Ihre Original-PDF zu verwenden und diese App zu ignorieren.",
        resultDidntCompressWell: " Die PDF wurde nicht gut komprimiert.",
        resultBecameBigger: " Die PDF wurde größer.",
        resultAppPurpose: "Diese App eignet sich am besten für gescannte Dokumente mit einem kontrastreichen Schwarz-Weiß-Erscheinungsbild (Sie müssen eine andere App zum Scannen verwenden). Wenn die PDF bereits gut optimiert wurde, kann diese App nicht helfen. Diese App existiert nur, weil die meisten verfügbaren PDF-Scanner-Apps das schön aussehende Ergebnis mit ineffizienter JPEG-Kompression anstelle der effizienten CCITT G4-Kompression speichern.",
        resultDitheringNote: "Dithering verschlechtert die Kompression, ist aber manchmal für Grafiken oder kontrastarmen Text notwendig.",
        resultDitheringAdvice: " Erwägen Sie, kein Dithering zu verwenden oder Dithering nur bei ausgewählten Seiten zu verwenden, z.B. wo Grafiken vorhanden sind. Text ist normalerweise ohne Dithering am besten.",
        advancedTricks: "Erweiterte technologische Tricks",
        useJBIG2Label: "Verlustbehaftete JBIG2-Kompression anstelle von CCITT G4 verwenden",
        jbig2Warning: "⚠️ Kompression durch Verwendung von JBIG2-Kompression anstelle von CCITT G4-Kompression verbessern. Kleine ähnliche Zeichen können verwechselt werden (z.B. 6 mit 8). Alte Geräte können das PDF möglicherweise nicht öffnen.",
        preserveRotationLabel: "Seitenausrichtung beibehalten versuchen",
        metadataSection: "Metadaten",
        includeTimestampLabel: "Erstellungs- und Änderungszeitstempel einbeziehen",
        ramWarningHigh: "Hinweis: Die Kombination aus Seitenzahl und DPI-Auflösung für diese Datei führt zu einem hohen geschätzten Ressourcenverbrauch ({ram}). Die Verarbeitung kann langsam sein und große Ausgabedateien erzeugen.",
        ramWarningCritical: "Warnung: Die Kombination aus Seitenzahl und DPI-Auflösung für diese Datei führt zu einem sehr hohen geschätzten Ressourcenverbrauch ({ram}). Ihr Gerät kann heiß werden, langsam laufen oder der Speicher kann voll werden. Dies wird typischerweise nur für kurze Dokumente empfohlen oder wenn PDFs in ein Basis-Format konvertiert werden müssen, um Druckprobleme zu umgehen.",
        jbig2DisabledMpix: "JBIG2 ist deaktiviert: Die gesamte Bilddatenmenge ({mpix} Megapixel, aus Seitengröße × DPI × {pages} Seiten) überschreitet das 475-Megapixel-Limit des JBIG2-Encoders. Verringern Sie die DPI oder verwenden Sie weniger Seiten, um JBIG2 zu aktivieren.",
        jbig2DisabledPages: "JBIG2 ist deaktiviert: Dieses PDF hat {pages} Seiten und überschreitet das 120-Seiten-Limit des JBIG2-Encoders. Das Symbolwörterbuch des Encoders kann nicht mehr als 120 Seiten zuverlässig verarbeiten.",
        ramOverrideAcceptRisk: " (mein Gerät kann den Speicher überlasten oder heiß werden, die Anwendung könnte abstürzen, und ich akzeptiere dieses Risiko, lass mich einfach den Komprimieren-Button klicken)",
        fileInfoPageCount: "Seitenanzahl: {pages}",
        fileInfoFileSize: "Dateigröße: {size}",
        inputHint: "Diese App ist für PDFs mit Scans von Papierdokumenten gedacht, die Sie in Schwarzweiß umwandeln und verkleinern möchten. Enthält Ihr PDF kopierbaren Text (z.B. Exporte aus Office-Anwendungen, E-Books, exportierte Webseiten), ist es wahrscheinlich bereits gut optimiert und diese App wird voraussichtlich keine guten Ergebnisse liefern. Ebenso führt eine erneute Komprimierung eines bereits mit CCITT G4, JBIG2 oder MRC komprimierten Scans zu Generationsverlust (Qualitätsverschlechterung durch Neukodierung) ohne wesentliche Größenreduzierung. Komprimieren Sie für beste Ergebnisse immer den ursprünglichen, nicht optimierten Scan.",
    },

    // Spanish
    es: {
        title: "Compresor PDF Monocromo G4",
        subtitle: "Comprima PDFs reduciendo colores a monocromo de 1 bit, ajustando la resolución DPI y usando la eficiente compresión CCITT Group 4 (ITU-T T.6, MMR o compresión Fax).",        privacyNotice: "🔒 Funciona 100% sin conexión. Sus PDFs nunca salen de su dispositivo.",
        chooseFile: "Elegir archivo PDF",
        conversionMode: "Modo de conversión:",
        noDither: "Sin difuminado (Nítido)",
        dither: "Con difuminado (Suave)",
        ditherSelected: "Difuminar solo páginas seleccionadas",
        pageRangePlaceholder: "ej., 1, 3-5, 8, 10-12",
        pageRangeHint: "Introduzca números de página y rangos separados por comas",
        pageSize: "Tamaño de página:",
        pageSizeA4Portrait: "A4 Vertical",
        pageSizeA4Landscape: "A4 Horizontal",
        pageSizeLetterPortrait: "Letter Vertical",
        pageSizeLetterLandscape: "Letter Horizontal",
        pageSizeLegalPortrait: "US Legal Vertical",
        outputDpi: "DPI de salida (Resolución):",
        dpiStandard: "Estándar (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Mayor DPI = archivo más grande pero mejor calidad. Se recomienda 310 DPI.",
        compressButton: "Comprimir",
        processing: "Procesando...",
        credits: "Creado con PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Licenciado bajo Apache 2.0 • Ver licencias y atribuciones",
        about: "Sobre este proyecto • Un estudio de decisiones cuestionables",        lowQualityWarning: "Advertencia: Un DPI bajo puede resultar en mala calidad. El texto puede ser difícil de leer y se pueden perder detalles finos.",
        resultSaveButton: "Guardar el PDF resultante",
        resultRecommendIgnore: "Para este PDF en particular, recomendamos usar su PDF original e ignorar esta aplicación.",
        resultDidntCompressWell: " El PDF no se comprimió bien.",
        resultBecameBigger: " El PDF se hizo más grande.",
        resultAppPurpose: "Esta aplicación se utiliza mejor con documentos escaneados con apariencia de alto contraste en blanco y negro (debe usar otra aplicación para escanear). Si el PDF ya estaba bien optimizado, esta aplicación no puede ayudar. Esta aplicación existe solo porque la mayoría de las aplicaciones de escaneo PDF disponibles guardan el resultado de aspecto agradable con compresión JPEG ineficiente en lugar de la eficiente compresión CCITT G4.",
        resultDitheringNote: "El tramado empeora la compresión pero a veces es necesario para gráficos o texto de bajo contraste.",
        resultDitheringAdvice: " Considere no usar tramado, o usar tramado solo en páginas seleccionadas, por ejemplo, donde hay gráficos. El texto generalmente es mejor sin tramado.",
        advancedTricks: "Trucos tecnológicos avanzados",
        useJBIG2Label: "Usar compresión JBIG2 con pérdida en lugar de CCITT G4",
        jbig2Warning: "⚠️ Mejore la compresión usando compresión JBIG2 en lugar de compresión CCITT G4. Caracteres pequeños similares pueden confundirse (p.ej. 6 con 8). Dispositivos antiguos podrían no abrir el PDF.",
        preserveRotationLabel: "Intentar preservar la rotación de página",
        metadataSection: "Metadatos",
        includeTimestampLabel: "Incluir sellos de Creación y Modificación",
        ramWarningHigh: "Nota: La combinación de número de páginas y resolución DPI para este archivo resulta en un alto uso estimado de recursos ({ram}). El procesamiento puede ser lento y producir archivos de salida grandes.",
        ramWarningCritical: "Advertencia: La combinación de número de páginas y resolución DPI para este archivo resulta en un uso estimado de recursos muy alto ({ram}). Su dispositivo puede calentarse, funcionar lentamente o quedarse sin memoria. Esto solo se recomienda típicamente para documentos cortos o al convertir PDFs a un formato básico para solucionar problemas de impresión.",
        jbig2DisabledMpix: "JBIG2 está desactivado: los datos de imagen totales ({mpix} megapíxeles, de tamaño de página × DPI × {pages} páginas) superan el límite de 475 megapíxeles del codificador JBIG2. Reduzca los DPI o use menos páginas para activar JBIG2.",
        jbig2DisabledPages: "JBIG2 está desactivado: este PDF tiene {pages} páginas, superando el límite de 120 páginas del codificador JBIG2. El diccionario de símbolos del codificador no puede manejar más de 120 páginas de manera confiable.",
        ramOverrideAcceptRisk: " (mi dispositivo puede quedarse sin memoria o calentarse, la aplicación podría fallar, y acepto ese riesgo, solo déjame hacer clic en el botón Comprimir)",
        fileInfoPageCount: "Número de páginas: {pages}",
        fileInfoFileSize: "Tamaño del archivo: {size}",
        inputHint: "Esta aplicación está diseñada para PDFs con escaneos de documentos en papel que desea convertir a blanco y negro y reducir su tamaño. Si su PDF contiene texto copiable (exportaciones de aplicaciones ofimáticas, libros digitales, páginas web exportadas), probablemente ya está bien optimizado y esta aplicación no dará buenos resultados. Del mismo modo, si su PDF escaneado ya fue comprimido con CCITT G4, JBIG2 o MRC, recomprimirlo aquí causará pérdida generacional (degradación de calidad por recodificación) sin reducción significativa del tamaño. Para mejores resultados, comprima siempre el escaneo original sin optimizar.",
    },

    // Portuguese
    pt: {
        title: "Compressor PDF Monocromático G4",
        subtitle: "Comprima PDFs reduzindo cores para monocromático de 1 bit, ajustando resolução DPI e usando a eficiente compressão CCITT Group 4 (ITU-T T.6, MMR ou compressão Fax).",        privacyNotice: "🔒 Funciona 100% offline. Seus PDFs nunca saem do seu dispositivo.",
        chooseFile: "Escolher arquivo PDF",
        conversionMode: "Modo de conversão:",
        noDither: "Sem pontilhamento (Nítido)",
        dither: "Com pontilhamento (Suave)",
        ditherSelected: "Pontilhar apenas páginas selecionadas",
        pageRangePlaceholder: "ex., 1, 3-5, 8, 10-12",
        pageRangeHint: "Digite números de página e intervalos separados por vírgulas",
        pageSize: "Tamanho da página:",
        pageSizeA4Portrait: "A4 Retrato",
        pageSizeA4Landscape: "A4 Horizontal",
        pageSizeLetterPortrait: "Letter Retrato",
        pageSizeLetterLandscape: "Letter Horizontal",
        pageSizeLegalPortrait: "US Legal Retrato",
        outputDpi: "DPI de saída (Resolução):",
        dpiStandard: "Padrão (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Maior DPI = arquivo maior, mas melhor qualidade. 310 DPI recomendado.",
        compressButton: "Comprimir",
        processing: "Processando...",
        credits: "Criado com PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Licenciado sob Apache 2.0 • Ver licenças e atribuições",
        about: "Sobre este projeto • Um estudo de decisões questionáveis",        lowQualityWarning: "Aviso: DPI baixo pode resultar em má qualidade. O texto pode ser difícil de ler e detalhes finos podem ser perdidos.",
        resultSaveButton: "Salvar o PDF resultante",
        resultRecommendIgnore: "Para este PDF em particular, recomendamos usar seu PDF original e ignorar este aplicativo.",
        resultDidntCompressWell: " O PDF não comprimiu bem.",
        resultBecameBigger: " O PDF ficou maior.",
        resultAppPurpose: "Este aplicativo é melhor usado com documentos digitalizados com aparência de alto contraste em preto e branco (você precisa usar outro aplicativo para digitalizar). Se o PDF já estava bem otimizado, este aplicativo não pode ajudar. Este aplicativo existe apenas porque a maioria dos aplicativos de scanner PDF disponíveis salva o resultado de boa aparência com compressão JPEG ineficiente em vez da eficiente compressão CCITT G4.",
        resultDitheringNote: "O pontilhamento piora a compressão, mas às vezes é necessário para gráficos ou texto de baixo contraste.",
        resultDitheringAdvice: " Considere não usar pontilhamento, ou usar pontilhamento apenas em páginas selecionadas, por exemplo, onde há gráficos. O texto geralmente é melhor sem pontilhamento.",
        advancedTricks: "Truques tecnológicos avançados",
        useJBIG2Label: "Usar compressão JBIG2 com perdas em vez de CCITT G4",
        jbig2Warning: "⚠️ Melhore a compressão usando compressão JBIG2 em vez de compressão CCITT G4. Caracteres pequenos semelhantes podem ser confundidos (por exemplo, 6 com 8). Dispositivos antigos podem não conseguir abrir o PDF.",
        preserveRotationLabel: "Tentar preservar a rotação da página",
        metadataSection: "Metadados",
        includeTimestampLabel: "Incluir carimbos de data/hora de Criação e Modificação",
        ramWarningHigh: "Nota: A combinação de número de páginas e resolução DPI para este arquivo resulta em alto uso estimado de recursos ({ram}). O processamento pode ser lento e produzir arquivos de saída grandes.",
        ramWarningCritical: "Aviso: A combinação de número de páginas e resolução DPI para este arquivo resulta em uso estimado de recursos muito alto ({ram}). Seu dispositivo pode esquentar, ficar lento ou ficar sem memória. Isso é tipicamente recomendado apenas para documentos curtos ou ao converter PDFs para um formato básico para contornar problemas de impressão.",
        jbig2DisabledMpix: "JBIG2 está desativado: o total de dados de imagem ({mpix} megapixels, de tamanho da página × DPI × {pages} páginas) excede o limite de 475 megapixels do codificador JBIG2. Reduza o DPI ou use menos páginas para ativar o JBIG2.",
        jbig2DisabledPages: "JBIG2 está desativado: este PDF tem {pages} páginas, excedendo o limite de 120 páginas do codificador JBIG2. O dicionário de símbolos do codificador não pode lidar com mais de 120 páginas de forma confiável.",
        ramOverrideAcceptRisk: " (meu dispositivo pode ficar sem memória ou esquentar, o aplicativo pode travar, e eu aceito esse risco, apenas me deixe clicar no botão Comprimir)",
        fileInfoPageCount: "Número de páginas: {pages}",
        fileInfoFileSize: "Tamanho do arquivo: {size}",
        inputHint: "Este aplicativo é projetado para PDFs contendo digitalizações de documentos em papel que você deseja converter para preto e branco e reduzir o tamanho. Se seu PDF contém texto copiável (exportações de aplicativos de escritório, livros digitais, páginas web exportadas), provavelmente já está bem otimizado e este aplicativo não produzirá bons resultados. Da mesma forma, se seu PDF digitalizado já foi comprimido com CCITT G4, JBIG2 ou MRC, recomprimi-lo aqui causará perda geracional (degradação de qualidade por recodificação) sem redução significativa de tamanho. Para melhores resultados, sempre comprima a digitalização original não otimizada.",
    },

    // Czech
    cs: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF snížením barev na jednobitovou černobílou, úpravou DPI rozlišení a použitím efektivní CCITT Group 4 komprese (ITU-T T.6, MMR nebo Fax komprese).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zařízení.",
        chooseFile: "Vybrat PDF soubor",
        conversionMode: "Režim převodu:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylem (Hladké)",
        ditherSelected: "Rozptýlit pouze vybrané stránky",
        pageRangePlaceholder: "např. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadejte čísla stránek a rozsahy oddělené čárkami",
        pageSize: "Velikost stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šířku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šířku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupní DPI (Rozlišení):",
        dpiStandard: "Standardní (310 DPI)",
        dpiCustom: "Vlastní DPI",
        dpiHint: "Vyšší DPI = větší soubor, ale lepší kvalita. Doporučeno 310 DPI.",
        compressButton: "Komprimovat",
        processing: "Zpracovávání...",
        credits: "Vytvořeno s PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Licencováno pod Apache 2.0 • Zobrazit licence a uvedení autorů",
        about: "O tomto projektu • Studie pochybných rozhodnutí",        lowQualityWarning: "Varování: Nízké DPI může vést ke špatné kvalitě. Text může být obtížně čitelný a jemné detaily mohou být ztraceny.",
        resultSaveButton: "Uložit výsledné PDF",
        resultRecommendIgnore: "Pro tento konkrétní PDF doporučujeme použít váš původní PDF a tuto aplikaci ignorovat.",
        resultDidntCompressWell: " PDF se dobře nekomprimovalo.",
        resultBecameBigger: " PDF se zvětšilo.",
        resultAppPurpose: "Tato aplikace se nejlépe používá se skenovanými dokumenty s kontrastním černobílým vzhledem (musíte použít jinou aplikaci pro skenování). Pokud byl PDF již dobře optimalizován, tato aplikace nemůže pomoci. Tato aplikace existuje pouze proto, že většina dostupných aplikací pro skenování PDF ukládá pěkně vypadající výsledek s neefektivní kompresí JPEG místo efektivní komprese CCITT G4.",
        resultDitheringNote: "Rozptyl zhoršuje kompresi, ale někdy je nutný pro grafiku nebo text s nízkým kontrastem.",
        resultDitheringAdvice: " Zvažte nepoužívání rozptylu nebo použití rozptylu pouze na vybraných stránkách, např. kde jsou grafiky. Text je obvykle nejlepší bez rozptylu.",
        advancedTricks: "Pokročilé technologické triky",
        useJBIG2Label: "Použít ztrátovou kompresi JBIG2 místo CCITT G4",
        jbig2Warning: "⚠️ Vylepšete kompresi pomocí komprese JBIG2 místo komprese CCITT G4. Malé podobné znaky mohou být zaměněny (např. 6 s 8). Stará zařízení nemusí být schopna otevřít PDF.",
        preserveRotationLabel: "Pokusit se zachovat otočení stránky",
        metadataSection: "Metadata",
        includeTimestampLabel: "Zahrnout časová razítka Vytvoření a Úpravy",
        ramWarningHigh: "Poznámka: Kombinace počtu stránek a rozlišení DPI pro tento soubor vede k vysokému odhadovanému využití zdrojů ({ram}). Zpracování může být pomalé a vytvořit velké výstupní soubory.",
        ramWarningCritical: "Varování: Kombinace počtu stránek a rozlišení DPI pro tento soubor vede k velmi vysokému odhadovanému využití zdrojů ({ram}). Vaše zařízení se může přehřát, zpomalit nebo mu může dojít paměť. Toto je doporučeno pouze pro krátké dokumenty nebo při převodu PDF do základního formátu k obejití problémů s tiskem.",
        jbig2DisabledMpix: "JBIG2 je zakázáno: celkový objem obrazových dat ({mpix} megapixelů, z velikosti stránky × DPI × {pages} stránek) překračuje limit 475 megapixelů kodéru JBIG2. Snižte DPI nebo použijte méně stránek pro povolení JBIG2.",
        jbig2DisabledPages: "JBIG2 je zakázáno: tento PDF má {pages} stránek, což překračuje limit 120 stránek kodéru JBIG2. Slovník symbolů kodéru nemůže spolehlivě zpracovat více než 120 stránek.",
        ramOverrideAcceptRisk: " (mé zařízení může dojít paměť nebo se přehřát, aplikace může spadnout, a přijímám toto riziko, prostě mě nechte kliknout na tlačítko Komprimovat)",
        fileInfoPageCount: "Počet stránek: {pages}",
        fileInfoFileSize: "Velikost souboru: {size}",
        inputHint: "Tato aplikace je určena pro PDF soubory obsahující skeny papírových dokumentů, které chcete převést na černobílé a zmenšit jejich velikost. Pokud váš PDF obsahuje kopírovatelný text (exporty z kancelářských aplikací, e-knihy, exportované webové stránky), je pravděpodobně již dobře optimalizován a tato aplikace pravděpodobně nepřinese dobré výsledky. Podobně, pokud byl váš naskenovaný PDF již komprimován pomocí CCITT G4, JBIG2 nebo MRC, opětovná komprese zde způsobí generační ztrátu (zhoršení kvality při překódování) bez výrazného zmenšení velikosti. Pro nejlepší výsledky vždy komprimujte původní neoptimalizovaný sken.",
    },

    // Slovak
    sk: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF znížením farieb na jednobitovú čiernobielu, úpravou DPI rozlíšenia a použitím efektívnej CCITT Group 4 kompresie (ITU-T T.6, MMR alebo Fax kompresia).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zariadenie.",
        chooseFile: "Vybrať PDF súbor",
        conversionMode: "Režim konverzie:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylom (Hladké)",
        ditherSelected: "Rozptyliť len vybrané strany",
        pageRangePlaceholder: "napr. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadajte čísla strán a rozsahy oddelené čiarkami",
        pageSize: "Veľkosť stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šírku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šírku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupné DPI (Rozlíšenie):",
        dpiStandard: "Štandardné (310 DPI)",
        dpiCustom: "Vlastné DPI",
        dpiHint: "Vyššie DPI = väčší súbor, ale lepšia kvalita. Odporúčané 310 DPI.",
        compressButton: "Komprimovať",
        processing: "Spracovávanie...",
        credits: "Vytvorené s PDF.js • pako • G4Enc • jbig2enc • Leptonica",
        license: "Licencované pod Apache 2.0 • Zobraziť licencie a uvedenie autorov",
        about: "O tomto projekte • Štúdia pochybných rozhodnutí",        lowQualityWarning: "Varovanie: Nízke DPI môže viesť k zlej kvalite. Text môže byť ťažko čitateľný a jemné detaily môžu byť stratené.",
        resultSaveButton: "Uložiť výsledné PDF",
        resultRecommendIgnore: "Pre tento konkrétny PDF odporúčame použiť váš pôvodný PDF a túto aplikáciu ignorovať.",
        resultDidntCompressWell: " PDF sa dobre nekomprimovalo.",
        resultBecameBigger: " PDF sa zväčšilo.",
        resultAppPurpose: "Táto aplikácia sa najlepšie používa so skenovanými dokumentmi s kontrastným čierno-bielym vzhľadom (musíte použiť inú aplikáciu na skenovanie). Ak bol PDF už dobre optimalizovaný, táto aplikácia nemôže pomôcť. Táto aplikácia existuje len preto, že väčšina dostupných aplikácií pre skenovanie PDF ukladá pekne vyzerajúci výsledok s neefektívnou kompresiou JPEG namiesto efektívnej kompresie CCITT G4.",
        resultDitheringNote: "Rozptyl zhoršuje kompresiu, ale niekedy je nutný pre grafiku alebo text s nízkym kontrastom.",
        resultDitheringAdvice: " Zvážte nepoužívanie rozptylu alebo použitie rozptylu len na vybraných stránkach, napr. kde sú grafiky. Text je zvyčajne najlepší bez rozptylu.",
        advancedTricks: "Pokročilé technologické triky",
        useJBIG2Label: "Použiť stratovú kompresiu JBIG2 namiesto CCITT G4",
        jbig2Warning: "⚠️ Vylepšite kompresiu pomocou kompresie JBIG2 namiesto kompresie CCITT G4. Malé podobné znaky môžu byť zamenené (napr. 6 s 8). Staré zariadenia nemusia byť schopné otvoriť PDF.",
        preserveRotationLabel: "Pokúsiť sa zachovať otočenie strany",
        metadataSection: "Metadáta",
        includeTimestampLabel: "Zahrnúť časové pečiatky Vytvorenia a Úpravy",
        ramWarningHigh: "Poznámka: Kombinácia počtu strán a rozlíšenia DPI pre tento súbor vedie k vysokému odhadovanému využitiu zdrojov ({ram}). Spracovanie môže byť pomalé a vytvoriť veľké výstupné súbory.",
        ramWarningCritical: "Varovanie: Kombinácia počtu strán a rozlíšenia DPI pre tento súbor vedie k veľmi vysokému odhadovanému využitiu zdrojov ({ram}). Vaše zariadenie sa môže prehriať, spomaliť alebo mu môže dôjsť pamäť. Toto je odporúčané len pre krátke dokumenty alebo pri prevode PDF do základného formátu na obídenie problémov s tlačou.",
        jbig2DisabledMpix: "JBIG2 je zakázané: celkový objem obrazových dát ({mpix} megapixelov, z veľkosti stránky × DPI × {pages} strán) prekračuje limit 475 megapixelov kodéra JBIG2. Znížte DPI alebo použite menej strán na povolenie JBIG2.",
        jbig2DisabledPages: "JBIG2 je zakázané: tento PDF má {pages} strán, čo prekračuje limit 120 strán kodéra JBIG2. Slovník symbolov kodéra nemôže spoľahlivo spracovať viac než 120 strán.",
        ramOverrideAcceptRisk: " (moje zariadenie môže dôjsť pamäť alebo sa prehriať, aplikácia môže spadnúť, a prijímam toto riziko, jednoducho ma nechajte kliknúť na tlačidlo Komprimovať)",
        fileInfoPageCount: "Počet strán: {pages}",
        fileInfoFileSize: "Veľkosť súboru: {size}",
        inputHint: "Táto aplikácia je určená pre PDF súbory obsahujúce skeny papierových dokumentov, ktoré chcete previesť na čiernobiele a zmenšiť ich veľkosť. Ak váš PDF obsahuje kopírovateľný text (exporty z kancelárskych aplikácií, e-knihy, exportované webové stránky), je pravdepodobne už dobre optimalizovaný a táto aplikácia pravdepodobne neprinesie dobré výsledky. Podobne, ak bol váš naskenovaný PDF už komprimovaný pomocou CCITT G4, JBIG2 alebo MRC, opätovná kompresia tu spôsobí generačnú stratu (zhoršenie kvality pri prekódovaní) bez výrazného zmenšenia veľkosti. Pre najlepšie výsledky vždy komprimujte pôvodný neoptimalizovaný sken.",
    },

    // Continue in next file due to length...
};

/**
 * Normalize a locale tag to proper BCP 47 casing:
 *   language (lowercase) - Script (titlecase) - REGION (uppercase)
 * e.g. "zh-hans-cn" → "zh-Hans-CN", "MN-MONG" → "mn-Mong"
 */
function normalizeBCP47(tag) {
    var parts = tag.split('-');
    parts[0] = parts[0].toLowerCase();
    for (var i = 1; i < parts.length; i++) {
        if (parts[i].length === 4) {
            // Script subtag: Title case (e.g., Hans, Mong, Cyrl, Latn)
            parts[i] = parts[i][0].toUpperCase() + parts[i].slice(1).toLowerCase();
        } else if (parts[i].length === 2) {
            // Region subtag: UPPERCASE (e.g., US, CN, MN)
            parts[i] = parts[i].toUpperCase();
        } else {
            // Language or other: lowercase (e.g., fil)
            parts[i] = parts[i].toLowerCase();
        }
    }
    return parts.join('-');
}

// Language detection with regional fallback
function detectLanguage() {
    // Get browser language(s)
    const languages = navigator.languages || [navigator.language || navigator.userLanguage || 'en'];

    for (let locale of languages) {
        locale = normalizeBCP47(locale);

        // Try exact match first
        if (TRANSLATIONS[locale]) {
            return locale;
        }

        // Try with fallback map
        if (LOCALE_FALLBACK[locale] && TRANSLATIONS[LOCALE_FALLBACK[locale]]) {
            return LOCALE_FALLBACK[locale];
        }

        // Try base language (en-US → en)
        const baseLang = locale.split('-')[0];
        if (TRANSLATIONS[baseLang]) {
            return baseLang;
        }
    }

    // Default to English
    return 'en';
}

// Apply translations
function applyTranslations(lang) {
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;

    // Set document language for screen readers
    document.documentElement.lang = lang;

    // Set RTL direction
    if (RTL_LANGUAGES.has(lang)) {
        document.body.setAttribute('dir', 'rtl');
    } else {
        document.body.setAttribute('dir', 'ltr');
    }

    // Translate all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (t[key]) {
            if (element.tagName === 'INPUT' && element.type === 'text') {
                element.placeholder = t[key];
            } else {
                element.textContent = t[key];
            }
        }
    });

    // Handle parameterized strings (like DPI dimensions)
    document.querySelectorAll('[data-i18n-template]').forEach(element => {
        const key = element.getAttribute('data-i18n-template');
        if (t[key]) {
            element.setAttribute('data-i18n-template-text', t[key]);
        }
    });
}
