/**
 * Internationalization (i18n) Module
 *
 * Translations for 30+ languages with regional variant support
 * RTL support for Arabic and Hebrew
 *
 * Note: Translations generated by AI - native speaker review recommended
 */

// RTL languages
const RTL_LANGUAGES = new Set(['ar', 'he', 'ur', 'yi']);

// Locale fallback map: specific locale → fallback chain
const LOCALE_FALLBACK = {
    // German variants
    'de-AT': 'de', 'de-CH': 'de', 'de-BE': 'de', 'de-LI': 'de',
    // English variants
    'en-GB': 'en', 'en-US': 'en', 'en-AU': 'en', 'en-NZ': 'en', 'en-CA': 'en', 'en-IN': 'en', 'en-ZA': 'en',
    // Spanish variants
    'es-MX': 'es', 'es-AR': 'es', 'es-CO': 'es', 'es-CL': 'es', 'es-PE': 'es', 'es-VE': 'es',
    // Portuguese variants
    'pt-BR': 'pt', 'pt-PT': 'pt',
    // French variants
    'fr-CA': 'fr', 'fr-BE': 'fr', 'fr-CH': 'fr',
    // Chinese variants
    'zh-CN': 'zh-Hans', 'zh-SG': 'zh-Hans', 'zh-Hans-CN': 'zh-Hans', 'zh-Hans-SG': 'zh-Hans',
    'zh-TW': 'zh-Hant', 'zh-HK': 'zh-Hant', 'zh-MO': 'zh-Hant', 'zh-Hant-TW': 'zh-Hant', 'zh-Hant-HK': 'zh-Hant',
    // Arabic variants
    'ar-EG': 'ar', 'ar-SA': 'ar', 'ar-MA': 'ar', 'ar-DZ': 'ar', 'ar-TN': 'ar', 'ar-SY': 'ar', 'ar-IQ': 'ar',
    // Swedish variants
    'sv-SE': 'sv', 'sv-FI': 'sv',
    // Norwegian variants
    'nb-NO': 'nb', 'nn-NO': 'nn', 'no-NO': 'nb',
    // Polish variants
    'pl-PL': 'pl', 'pl-US': 'pl',
    // Urdu variants
    'ur-PK': 'ur', 'ur-IN': 'ur',
    // Punjabi variants
    'pa-IN': 'pa', 'pa-PK': 'pa',
    // Indonesian variants
    'id-ID': 'id',
    // Tagalog/Filipino variants
    'tl-PH': 'tl', 'fil-PH': 'fil',
    // Vietnamese variants
    'vi-VN': 'vi',
    // Thai variants
    'th-TH': 'th',
    // Azerbaijani variants
    'az-AZ': 'az',
    // Uzbek variants
    'uz-UZ': 'uz',
    // Kazakh variants
    'kk-KZ': 'kk',
    // Georgian variants
    'ka-GE': 'ka',
    // Armenian variants
    'hy-AM': 'hy',
    // Belarusian variants
    'be-BY': 'be',
    // Mongolian variants
    'mn-MN': 'mn',
    // Amharic variants
    'am-ET': 'am',
    // Sinhala variants
    'si-LK': 'si',
    // Bosnian variants
    'bs-BA': 'bs',
    // Macedonian variants
    'mk-MK': 'mk',
    // Croatian variants
    'hr-HR': 'hr', 'hr-BA': 'hr',
    // Serbian variants - Cyrillic (default)
    'sr': 'sr-Cyrl', 'sr-RS': 'sr-Cyrl', 'sr-BA': 'sr-Cyrl', 'sr-ME': 'sr-Cyrl',
    'sr-Cyrl-RS': 'sr-Cyrl', 'sr-Cyrl-BA': 'sr-Cyrl', 'sr-Cyrl-ME': 'sr-Cyrl',
    // Serbian variants - Latin
    'sr-Latn-RS': 'sr-Latn', 'sr-Latn-BA': 'sr-Latn', 'sr-Latn-ME': 'sr-Latn',
    // Catalan variants
    'ca-ES': 'ca', 'ca-AD': 'ca',
    // Basque variants
    'eu-ES': 'eu',
    // Tibetan variants
    'bo-CN': 'bo', 'bo-IN': 'bo',
};

const TRANSLATIONS = {
    // English (default)
    en: {
        title: "PDF Monochrome G4 Compressor",
        subtitle: "Compress PDFs by reducing colors to bilevel monochrome, by reducing DPI resolution, and by using the efficient CCITT Group 4 compression inside PDF, also known as ITU-T T.6 or MMR or Fax compression.",
        privacyNotice: "🔒 Works 100% offline. Your PDFs never leave your device.",
        chooseFile: "Choose PDF File",
        conversionMode: "Conversion Mode:",
        noDither: "Non-dithered (Sharp)",
        dither: "Dithered (Smooth)",
        ditherSelected: "Dither only selected pages",
        pageRangePlaceholder: "e.g., 1, 3-5, 8, 10-12",
        pageRangeHint: "Enter page numbers and ranges separated by commas",
        pageSize: "Page Size:",
        pageSizeA4Portrait: "A4 Portrait",
        pageSizeA4Landscape: "A4 Landscape",
        pageSizeLetterPortrait: "Letter Portrait",
        pageSizeLetterLandscape: "Letter Landscape",
        pageSizeLegalPortrait: "US Legal Portrait",
        outputDpi: "Output DPI (Resolution):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Custom DPI",
        dpiHint: "Higher DPI = larger file size but better quality. 310 DPI recommended.",
        compressButton: "Compress to G4",
        processing: "Processing...",
        credits: "Built with PDF.js • pako • G4Enc",
        license: "Licensed under Apache 2.0 • View Licenses & Attributions",
        about: "About This Project • A Study in Questionable Decisions",
        lowQualityWarning: "Warning: Low DPI may result in poor quality output. Text may be difficult to read and fine details may be lost.",
        highFilesizeWarning: "Warning: High DPI will result in larger file sizes. Processing may also take longer.",
        highComputeWarning: "Warning: Processing at DPI above 600 is computationally intensive. Your device may become hot, run slowly, or run out of memory. This high DPI setting is typically only needed when converting PDFs to a barebones format to work around printing stack issues with accented or non-Latin characters on simple printers or devices.",
    },

    // German
    de: {
        title: "PDF Monochrom G4 Kompressor",
        subtitle: "PDFs komprimieren durch Reduzierung auf Schwarzweiß, Anpassung der DPI-Auflösung und Verwendung der effizienten CCITT Group 4 Kompression (ITU-T T.6, MMR oder Fax-Kompression).",        privacyNotice: "🔒 Funktioniert 100% offline. Ihre PDFs verlassen niemals Ihr Gerät.",
        chooseFile: "PDF-Datei wählen",
        conversionMode: "Konvertierungsmodus:",
        noDither: "Ohne Dithering (Scharf)",
        dither: "Mit Dithering (Weich)",
        ditherSelected: "Nur ausgewählte Seiten mit Dithering",
        pageRangePlaceholder: "z.B. 1, 3-5, 8, 10-12",
        pageRangeHint: "Seitenzahlen und Bereiche durch Kommas getrennt eingeben",
        pageSize: "Seitengröße:",
        pageSizeA4Portrait: "A4 Hochformat",
        pageSizeA4Landscape: "A4 Querformat",
        pageSizeLetterPortrait: "Letter Hochformat",
        pageSizeLetterLandscape: "Letter Querformat",
        pageSizeLegalPortrait: "US Legal Hochformat",
        outputDpi: "Ausgabe-DPI (Auflösung):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Benutzerdefiniert",
        dpiHint: "Höhere DPI = größere Datei, aber bessere Qualität. 310 DPI empfohlen.",
        compressButton: "Zu G4 komprimieren",
        processing: "Verarbeitung läuft...",
        credits: "Erstellt mit PDF.js • pako • G4Enc",
        license: "Lizenziert unter Apache 2.0 • Lizenzen & Zuordnungen ansehen",
        about: "Über dieses Projekt • Eine Studie fragwürdiger Entscheidungen",        lowQualityWarning: "Warnung: Niedrige DPI können zu schlechter Qualität führen. Text kann schwer lesbar sein und feine Details können verloren gehen.",
        highFilesizeWarning: "Warnung: Hohe DPI führen zu größeren Dateien. Die Verarbeitung kann auch länger dauern.",
        highComputeWarning: "Warnung: Verarbeitung bei über 600 DPI ist rechenintensiv. Ihr Gerät kann heiß werden, langsam laufen oder der Speicher kann voll werden. Diese hohe DPI-Einstellung ist normalerweise nur erforderlich, wenn PDFs in ein Basis-Format konvertiert werden müssen, um Druckprobleme mit Akzenten oder nicht-lateinischen Zeichen zu umgehen.",    },

    // Spanish
    es: {
        title: "Compresor PDF Monocromo G4",
        subtitle: "Comprima PDFs reduciendo colores a monocromo de 1 bit, ajustando la resolución DPI y usando la eficiente compresión CCITT Group 4 (ITU-T T.6, MMR o compresión Fax).",        privacyNotice: "🔒 Funciona 100% sin conexión. Sus PDFs nunca salen de su dispositivo.",
        chooseFile: "Elegir archivo PDF",
        conversionMode: "Modo de conversión:",
        noDither: "Sin difuminado (Nítido)",
        dither: "Con difuminado (Suave)",
        ditherSelected: "Difuminar solo páginas seleccionadas",
        pageRangePlaceholder: "ej., 1, 3-5, 8, 10-12",
        pageRangeHint: "Introduzca números de página y rangos separados por comas",
        pageSize: "Tamaño de página:",
        pageSizeA4Portrait: "A4 Vertical",
        pageSizeA4Landscape: "A4 Horizontal",
        pageSizeLetterPortrait: "Letter Vertical",
        pageSizeLetterLandscape: "Letter Horizontal",
        pageSizeLegalPortrait: "US Legal Vertical",
        outputDpi: "DPI de salida (Resolución):",
        dpiStandard: "Estándar (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Mayor DPI = archivo más grande pero mejor calidad. Se recomienda 310 DPI.",
        compressButton: "Comprimir a G4",
        processing: "Procesando...",
        credits: "Creado con PDF.js • pako • G4Enc",
        license: "Licenciado bajo Apache 2.0 • Ver licencias y atribuciones",
        about: "Sobre este proyecto • Un estudio de decisiones cuestionables",        lowQualityWarning: "Advertencia: Un DPI bajo puede resultar en mala calidad. El texto puede ser difícil de leer y se pueden perder detalles finos.",
        highFilesizeWarning: "Advertencia: Un DPI alto resultará en archivos más grandes. El procesamiento también puede tardar más.",
        highComputeWarning: "Advertencia: El procesamiento a más de 600 DPI es intensivo computacionalmente. Su dispositivo puede calentarse, funcionar lentamente o quedarse sin memoria. Esta configuración de DPI alto solo suele ser necesaria al convertir PDFs a un formato básico para evitar problemas de impresión con caracteres acentuados o no latinos.",    },

    // Portuguese
    pt: {
        title: "Compressor PDF Monocromático G4",
        subtitle: "Comprima PDFs reduzindo cores para monocromático de 1 bit, ajustando resolução DPI e usando a eficiente compressão CCITT Group 4 (ITU-T T.6, MMR ou compressão Fax).",        privacyNotice: "🔒 Funciona 100% offline. Seus PDFs nunca saem do seu dispositivo.",
        chooseFile: "Escolher arquivo PDF",
        conversionMode: "Modo de conversão:",
        noDither: "Sem pontilhamento (Nítido)",
        dither: "Com pontilhamento (Suave)",
        ditherSelected: "Pontilhar apenas páginas selecionadas",
        pageRangePlaceholder: "ex., 1, 3-5, 8, 10-12",
        pageRangeHint: "Digite números de página e intervalos separados por vírgulas",
        pageSize: "Tamanho da página:",
        pageSizeA4Portrait: "A4 Retrato",
        pageSizeA4Landscape: "A4 Paisagem",
        pageSizeLetterPortrait: "Letter Retrato",
        pageSizeLetterLandscape: "Letter Paisagem",
        pageSizeLegalPortrait: "US Legal Retrato",
        outputDpi: "DPI de saída (Resolução):",
        dpiStandard: "Padrão (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Maior DPI = arquivo maior, mas melhor qualidade. 310 DPI recomendado.",
        compressButton: "Comprimir para G4",
        processing: "Processando...",
        credits: "Criado com PDF.js • pako • G4Enc",
        license: "Licenciado sob Apache 2.0 • Ver licenças e atribuições",
        about: "Sobre este projeto • Um estudo de decisões questionáveis",        lowQualityWarning: "Aviso: DPI baixo pode resultar em má qualidade. O texto pode ser difícil de ler e detalhes finos podem ser perdidos.",
        highFilesizeWarning: "Aviso: DPI alto resultará em arquivos maiores. O processamento também pode demorar mais.",
        highComputeWarning: "Aviso: O processamento acima de 600 DPI é intensivo computacionalmente. Seu dispositivo pode esquentar, ficar lento ou ficar sem memória. Esta configuração de DPI alto normalmente só é necessária ao converter PDFs para um formato básico para contornar problemas de impressão com caracteres acentuados ou não latinos.",    },

    // Czech
    cs: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF snížením barev na jednobitovou černobílou, úpravou DPI rozlišení a použitím efektivní CCITT Group 4 komprese (ITU-T T.6, MMR nebo Fax komprese).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zařízení.",
        chooseFile: "Vybrat PDF soubor",
        conversionMode: "Režim převodu:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylem (Hladké)",
        ditherSelected: "Rozptýlit pouze vybrané stránky",
        pageRangePlaceholder: "např. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadejte čísla stránek a rozsahy oddělené čárkami",
        pageSize: "Velikost stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šířku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šířku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupní DPI (Rozlišení):",
        dpiStandard: "Standardní (310 DPI)",
        dpiCustom: "Vlastní DPI",
        dpiHint: "Vyšší DPI = větší soubor, ale lepší kvalita. Doporučeno 310 DPI.",
        compressButton: "Komprimovat do G4",
        processing: "Zpracovávání...",
        credits: "Vytvořeno s PDF.js • pako • G4Enc",
        license: "Licencováno pod Apache 2.0 • Zobrazit licence a uvedení autorů",
        about: "O tomto projektu • Studie pochybných rozhodnutí",        lowQualityWarning: "Varování: Nízké DPI může vést ke špatné kvalitě. Text může být obtížně čitelný a jemné detaily mohou být ztraceny.",
        highFilesizeWarning: "Varování: Vysoké DPI povede k větším souborům. Zpracování může také trvat déle.",
        highComputeWarning: "Varování: Zpracování nad 600 DPI je výpočetně náročné. Vaše zařízení se může zahřát, zpomalit nebo dojít paměť. Toto vysoké nastavení DPI je obvykle potřeba pouze při převodu PDF do základního formátu pro obejití problémů s tiskem u akcentovaných nebo ne-latinských znaků.",    },

    // Slovak
    sk: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF znížením farieb na jednobitovú čiernobielu, úpravou DPI rozlíšenia a použitím efektívnej CCITT Group 4 kompresie (ITU-T T.6, MMR alebo Fax kompresia).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zariadenie.",
        chooseFile: "Vybrať PDF súbor",
        conversionMode: "Režim konverzie:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylom (Hladké)",
        ditherSelected: "Rozptyliť len vybrané strany",
        pageRangePlaceholder: "napr. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadajte čísla strán a rozsahy oddelené čiarkami",
        pageSize: "Veľkosť stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šírku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šírku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupné DPI (Rozlíšenie):",
        dpiStandard: "Štandardné (310 DPI)",
        dpiCustom: "Vlastné DPI",
        dpiHint: "Vyššie DPI = väčší súbor, ale lepšia kvalita. Odporúčané 310 DPI.",
        compressButton: "Komprimovať do G4",
        processing: "Spracovávanie...",
        credits: "Vytvorené s PDF.js • pako • G4Enc",
        license: "Licencované pod Apache 2.0 • Zobraziť licencie a uvedenie autorov",
        about: "O tomto projekte • Štúdia pochybných rozhodnutí",        lowQualityWarning: "Varovanie: Nízke DPI môže viesť k zlej kvalite. Text môže byť ťažko čitateľný a jemné detaily môžu byť stratené.",
        highFilesizeWarning: "Varovanie: Vysoké DPI povedie k väčším súborom. Spracovanie môže tiež trvať dlhšie.",
        highComputeWarning: "Varovanie: Spracovanie nad 600 DPI je výpočtovo náročné. Vaše zariadenie sa môže zahriať, spomaliť alebo dôjsť pamäť. Toto vysoké nastavenie DPI je zvyčajne potrebné len pri prevode PDF do základného formátu pre obídenie problémov s tlačou u akcentovaných alebo ne-latinských znakov.",    },

    // Continue in next file due to length...
};

// Language detection with regional fallback
function detectLanguage() {
    // Get browser language(s)
    const languages = navigator.languages || [navigator.language || navigator.userLanguage || 'en'];

    for (let locale of languages) {
        locale = locale.toLowerCase();

        // Try exact match first
        if (TRANSLATIONS[locale]) {
            return locale;
        }

        // Try with fallback map
        if (LOCALE_FALLBACK[locale] && TRANSLATIONS[LOCALE_FALLBACK[locale]]) {
            return LOCALE_FALLBACK[locale];
        }

        // Try base language (en-US → en)
        const baseLang = locale.split('-')[0];
        if (TRANSLATIONS[baseLang]) {
            return baseLang;
        }
    }

    // Default to English
    return 'en';
}

// Apply translations
function applyTranslations(lang) {
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;

    // Set RTL direction
    if (RTL_LANGUAGES.has(lang)) {
        document.body.setAttribute('dir', 'rtl');
    } else {
        document.body.setAttribute('dir', 'ltr');
    }

    // Translate all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (t[key]) {
            if (element.tagName === 'INPUT' && element.type === 'text') {
                element.placeholder = t[key];
            } else {
                element.textContent = t[key];
            }
        }
    });

    // Handle parameterized strings (like DPI dimensions)
    document.querySelectorAll('[data-i18n-template]').forEach(element => {
        const key = element.getAttribute('data-i18n-template');
        if (t[key]) {
            element.setAttribute('data-i18n-template-text', t[key]);
        }
    });
}
