/**
 * Internationalization (i18n) Module
 *
 * Translations for 30+ languages with regional variant support
 * RTL support for Arabic and Hebrew
 *
 * Note: Translations generated by AI - native speaker review recommended
 */

// RTL languages
const RTL_LANGUAGES = new Set(['ar', 'he', 'ur', 'yi']);

// Locale fallback map: specific locale → fallback chain
const LOCALE_FALLBACK = {
    // German variants
    'de-at': 'de', 'de-ch': 'de', 'de-be': 'de', 'de-li': 'de',
    // English variants
    'en-gb': 'en', 'en-us': 'en', 'en-au': 'en', 'en-nz': 'en', 'en-ca': 'en', 'en-in': 'en', 'en-za': 'en',
    // Spanish variants
    'es-mx': 'es', 'es-ar': 'es', 'es-co': 'es', 'es-cl': 'es', 'es-pe': 'es', 'es-ve': 'es',
    // Portuguese variants
    'pt-br': 'pt', 'pt-pt': 'pt',
    // French variants
    'fr-ca': 'fr', 'fr-be': 'fr', 'fr-ch': 'fr',
    // Chinese variants (keys must be lowercase to match detectLanguage)
    'zh': 'zh-hans',  // Plain 'zh' defaults to Simplified Chinese
    'zh-cn': 'zh-hans', 'zh-sg': 'zh-hans', 'zh-hans-cn': 'zh-hans', 'zh-hans-sg': 'zh-hans',
    'zh-tw': 'zh-hant', 'zh-hk': 'zh-hant', 'zh-mo': 'zh-hant', 'zh-hant-tw': 'zh-hant', 'zh-hant-hk': 'zh-hant',
    // Arabic variants
    'ar-eg': 'ar', 'ar-sa': 'ar', 'ar-ma': 'ar', 'ar-dz': 'ar', 'ar-tn': 'ar', 'ar-sy': 'ar', 'ar-iq': 'ar',
    // Swedish variants
    'sv-se': 'sv', 'sv-fi': 'sv',
    // Norwegian variants
    'nb-no': 'nb', 'nn-no': 'nn', 'no-no': 'nb',
    // Polish variants
    'pl-pl': 'pl', 'pl-us': 'pl',
    // Urdu variants
    'ur-pk': 'ur', 'ur-in': 'ur',
    // Punjabi variants
    'pa-in': 'pa', 'pa-pk': 'pa',
    // Indonesian variants
    'id-id': 'id',
    // Tagalog/Filipino variants
    'tl-ph': 'tl', 'fil-ph': 'tl', 'fil': 'tl',  // Android uses 'fil' but we have 'tl' translation
    // Vietnamese variants
    'vi-vn': 'vi',
    // Thai variants
    'th-th': 'th',
    // Azerbaijani variants
    'az-az': 'az',
    // Uzbek variants
    'uz-uz': 'uz',
    // Kazakh variants
    'kk-kz': 'kk',
    // Georgian variants
    'ka-ge': 'ka',
    // Armenian variants
    'hy-am': 'hy',
    // Belarusian variants
    'be-by': 'be',
    // Mongolian variants
    'mn-mn': 'mn',
    'mn-mong-mn': 'mn-mong', 'mn-mong-cn': 'mn-mong',
    // Note: Plain 'mn-Mong' without region is handled by exact match, but listed here for clarity
    // Amharic variants
    'am-et': 'am',
    // Sinhala variants
    'si-lk': 'si',
    // Bosnian variants
    'bs-ba': 'bs',
    // Macedonian variants
    'mk-mk': 'mk',
    // Croatian variants
    'hr-hr': 'hr', 'hr-ba': 'hr',
    // Serbian variants - Cyrillic (default)
    'sr': 'sr-cyrl', 'sr-rs': 'sr-cyrl', 'sr-ba': 'sr-cyrl', 'sr-me': 'sr-cyrl',
    'sr-cyrl-rs': 'sr-cyrl', 'sr-cyrl-ba': 'sr-cyrl', 'sr-cyrl-me': 'sr-cyrl',
    // Serbian variants - Latin
    'sr-latn-rs': 'sr-latn', 'sr-latn-ba': 'sr-latn', 'sr-latn-me': 'sr-latn',
    // Catalan variants
    'ca-es': 'ca', 'ca-ad': 'ca',
    // Basque variants
    'eu-es': 'eu',
    // Tibetan variants
    'bo-cn': 'bo', 'bo-in': 'bo',
};

const TRANSLATIONS = {
    // English (default)
    en: {
        title: "PDF Monochrome G4 Compressor",
        subtitle: "Compress PDFs by reducing colors to bilevel monochrome, by reducing DPI resolution, and by using the efficient CCITT Group 4 compression inside PDF, also known as ITU-T T.6 or MMR or Fax compression.",
        privacyNotice: "🔒 Works 100% offline. Your PDFs never leave your device.",
        chooseFile: "Choose PDF File",
        conversionMode: "Conversion Mode:",
        noDither: "Non-dithered (Sharp)",
        dither: "Dithered (Smooth)",
        ditherSelected: "Dither only selected pages",
        pageRangePlaceholder: "e.g., 1, 3-5, 8, 10-12",
        pageRangeHint: "Enter page numbers and ranges separated by commas",
        pageSize: "Page Size:",
        pageSizeA4Portrait: "A4 Portrait",
        pageSizeA4Landscape: "A4 Landscape",
        pageSizeLetterPortrait: "Letter Portrait",
        pageSizeLetterLandscape: "Letter Landscape",
        pageSizeLegalPortrait: "US Legal Portrait",
        outputDpi: "Output DPI (Resolution):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Custom DPI",
        dpiHint: "Higher DPI = larger file size but better quality. 310 DPI recommended.",
        compressButton: "Compress to G4",
        processing: "Processing...",
        credits: "Built with PDF.js • pako • G4Enc",
        license: "Licensed under Apache 2.0 • View Licenses & Attributions",
        about: "About This Project • A Study in Questionable Decisions",
        lowQualityWarning: "Warning: Low DPI may result in poor quality output. Text may be difficult to read and fine details may be lost.",
        highFilesizeWarning: "Warning: High DPI will result in larger file sizes. Processing may also take longer.",
        highComputeWarning: "Warning: Processing at DPI above 600 is computationally intensive. Your device may become hot, run slowly, or run out of memory. This high DPI setting is typically only needed when converting PDFs to a barebones format to work around printing stack issues with accented or non-Latin characters on simple printers or devices.",
        resultSaveButton: "Save the result PDF",
        resultRecommendIgnore: "For this particular PDF, we recommend using your original PDF and ignoring this app.",
        resultDidntCompressWell: " The PDF didn't compress well.",
        resultBecameBigger: " The PDF became bigger.",
        resultAppPurpose: "This app is best used with scanned documents with high-contrast black and white look (you have to use another app for the scanning). If the PDF was already optimized well, this app can't help. This app exists only because most available PDF scanner apps save the nicely-looking result with inefficient JPEG compression instead of the efficient CCITT G4 compression.",
        resultDitheringNote: "Dithering makes the compression worse but is sometimes necessary for graphics or low-contrast text.",
        resultDitheringAdvice: " Consider not using dithering, or using dithering only with selected pages, e.g. where some graphics are. Text is usually best without dithering.",
    },

    // German
    de: {
        title: "PDF Monochrom G4 Kompressor",
        subtitle: "PDFs komprimieren durch Reduzierung auf Schwarzweiß, Anpassung der DPI-Auflösung und Verwendung der effizienten CCITT Group 4 Kompression (ITU-T T.6, MMR oder Fax-Kompression).",        privacyNotice: "🔒 Funktioniert 100% offline. Ihre PDFs verlassen niemals Ihr Gerät.",
        chooseFile: "PDF-Datei wählen",
        conversionMode: "Konvertierungsmodus:",
        noDither: "Ohne Dithering (Scharf)",
        dither: "Mit Dithering (Weich)",
        ditherSelected: "Nur ausgewählte Seiten mit Dithering",
        pageRangePlaceholder: "z.B. 1, 3-5, 8, 10-12",
        pageRangeHint: "Seitenzahlen und Bereiche durch Kommas getrennt eingeben",
        pageSize: "Seitengröße:",
        pageSizeA4Portrait: "A4 Hochformat",
        pageSizeA4Landscape: "A4 Querformat",
        pageSizeLetterPortrait: "Letter Hochformat",
        pageSizeLetterLandscape: "Letter Querformat",
        pageSizeLegalPortrait: "US Legal Hochformat",
        outputDpi: "Ausgabe-DPI (Auflösung):",
        dpiStandard: "Standard (310 DPI)",
        dpiCustom: "Benutzerdefiniert",
        dpiHint: "Höhere DPI = größere Datei, aber bessere Qualität. 310 DPI empfohlen.",
        compressButton: "Zu G4 komprimieren",
        processing: "Verarbeitung läuft...",
        credits: "Erstellt mit PDF.js • pako • G4Enc",
        license: "Lizenziert unter Apache 2.0 • Lizenzen & Zuordnungen ansehen",
        about: "Über dieses Projekt • Eine Studie fragwürdiger Entscheidungen",        lowQualityWarning: "Warnung: Niedrige DPI können zu schlechter Qualität führen. Text kann schwer lesbar sein und feine Details können verloren gehen.",
        highFilesizeWarning: "Warnung: Hohe DPI führen zu größeren Dateien. Die Verarbeitung kann auch länger dauern.",
        highComputeWarning: "Warnung: Verarbeitung bei über 600 DPI ist rechenintensiv. Ihr Gerät kann heiß werden, langsam laufen oder der Speicher kann voll werden. Diese hohe DPI-Einstellung ist normalerweise nur erforderlich, wenn PDFs in ein Basis-Format konvertiert werden müssen, um Druckprobleme mit Akzenten oder nicht-lateinischen Zeichen zu umgehen.",
        resultSaveButton: "Ergebnis-PDF speichern",
        resultRecommendIgnore: "Für diese spezielle PDF empfehlen wir, Ihre Original-PDF zu verwenden und diese App zu ignorieren.",
        resultDidntCompressWell: " Die PDF wurde nicht gut komprimiert.",
        resultBecameBigger: " Die PDF wurde größer.",
        resultAppPurpose: "Diese App eignet sich am besten für gescannte Dokumente mit einem kontrastreichen Schwarz-Weiß-Erscheinungsbild (Sie müssen eine andere App zum Scannen verwenden). Wenn die PDF bereits gut optimiert wurde, kann diese App nicht helfen. Diese App existiert nur, weil die meisten verfügbaren PDF-Scanner-Apps das schön aussehende Ergebnis mit ineffizienter JPEG-Kompression anstelle der effizienten CCITT G4-Kompression speichern.",
        resultDitheringNote: "Dithering verschlechtert die Kompression, ist aber manchmal für Grafiken oder kontrastarmen Text notwendig.",
        resultDitheringAdvice: " Erwägen Sie, kein Dithering zu verwenden oder Dithering nur bei ausgewählten Seiten zu verwenden, z.B. wo Grafiken vorhanden sind. Text ist normalerweise ohne Dithering am besten.",
    },

    // Spanish
    es: {
        title: "Compresor PDF Monocromo G4",
        subtitle: "Comprima PDFs reduciendo colores a monocromo de 1 bit, ajustando la resolución DPI y usando la eficiente compresión CCITT Group 4 (ITU-T T.6, MMR o compresión Fax).",        privacyNotice: "🔒 Funciona 100% sin conexión. Sus PDFs nunca salen de su dispositivo.",
        chooseFile: "Elegir archivo PDF",
        conversionMode: "Modo de conversión:",
        noDither: "Sin difuminado (Nítido)",
        dither: "Con difuminado (Suave)",
        ditherSelected: "Difuminar solo páginas seleccionadas",
        pageRangePlaceholder: "ej., 1, 3-5, 8, 10-12",
        pageRangeHint: "Introduzca números de página y rangos separados por comas",
        pageSize: "Tamaño de página:",
        pageSizeA4Portrait: "A4 Vertical",
        pageSizeA4Landscape: "A4 Horizontal",
        pageSizeLetterPortrait: "Letter Vertical",
        pageSizeLetterLandscape: "Letter Horizontal",
        pageSizeLegalPortrait: "US Legal Vertical",
        outputDpi: "DPI de salida (Resolución):",
        dpiStandard: "Estándar (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Mayor DPI = archivo más grande pero mejor calidad. Se recomienda 310 DPI.",
        compressButton: "Comprimir a G4",
        processing: "Procesando...",
        credits: "Creado con PDF.js • pako • G4Enc",
        license: "Licenciado bajo Apache 2.0 • Ver licencias y atribuciones",
        about: "Sobre este proyecto • Un estudio de decisiones cuestionables",        lowQualityWarning: "Advertencia: Un DPI bajo puede resultar en mala calidad. El texto puede ser difícil de leer y se pueden perder detalles finos.",
        highFilesizeWarning: "Advertencia: Un DPI alto resultará en archivos más grandes. El procesamiento también puede tardar más.",
        highComputeWarning: "Advertencia: El procesamiento a más de 600 DPI es intensivo computacionalmente. Su dispositivo puede calentarse, funcionar lentamente o quedarse sin memoria. Esta configuración de DPI alto solo suele ser necesaria al convertir PDFs a un formato básico para evitar problemas de impresión con caracteres acentuados o no latinos.",
        resultSaveButton: "Guardar el PDF resultante",
        resultRecommendIgnore: "Para este PDF en particular, recomendamos usar su PDF original e ignorar esta aplicación.",
        resultDidntCompressWell: " El PDF no se comprimió bien.",
        resultBecameBigger: " El PDF se hizo más grande.",
        resultAppPurpose: "Esta aplicación se utiliza mejor con documentos escaneados con apariencia de alto contraste en blanco y negro (debe usar otra aplicación para escanear). Si el PDF ya estaba bien optimizado, esta aplicación no puede ayudar. Esta aplicación existe solo porque la mayoría de las aplicaciones de escaneo PDF disponibles guardan el resultado de aspecto agradable con compresión JPEG ineficiente en lugar de la eficiente compresión CCITT G4.",
        resultDitheringNote: "El tramado empeora la compresión pero a veces es necesario para gráficos o texto de bajo contraste.",
        resultDitheringAdvice: " Considere no usar tramado, o usar tramado solo en páginas seleccionadas, por ejemplo, donde hay gráficos. El texto generalmente es mejor sin tramado.",
    },

    // Portuguese
    pt: {
        title: "Compressor PDF Monocromático G4",
        subtitle: "Comprima PDFs reduzindo cores para monocromático de 1 bit, ajustando resolução DPI e usando a eficiente compressão CCITT Group 4 (ITU-T T.6, MMR ou compressão Fax).",        privacyNotice: "🔒 Funciona 100% offline. Seus PDFs nunca saem do seu dispositivo.",
        chooseFile: "Escolher arquivo PDF",
        conversionMode: "Modo de conversão:",
        noDither: "Sem pontilhamento (Nítido)",
        dither: "Com pontilhamento (Suave)",
        ditherSelected: "Pontilhar apenas páginas selecionadas",
        pageRangePlaceholder: "ex., 1, 3-5, 8, 10-12",
        pageRangeHint: "Digite números de página e intervalos separados por vírgulas",
        pageSize: "Tamanho da página:",
        pageSizeA4Portrait: "A4 Retrato",
        pageSizeA4Landscape: "A4 Horizontal",
        pageSizeLetterPortrait: "Letter Retrato",
        pageSizeLetterLandscape: "Letter Horizontal",
        pageSizeLegalPortrait: "US Legal Retrato",
        outputDpi: "DPI de saída (Resolução):",
        dpiStandard: "Padrão (310 DPI)",
        dpiCustom: "DPI personalizado",
        dpiHint: "Maior DPI = arquivo maior, mas melhor qualidade. 310 DPI recomendado.",
        compressButton: "Comprimir para G4",
        processing: "Processando...",
        credits: "Criado com PDF.js • pako • G4Enc",
        license: "Licenciado sob Apache 2.0 • Ver licenças e atribuições",
        about: "Sobre este projeto • Um estudo de decisões questionáveis",        lowQualityWarning: "Aviso: DPI baixo pode resultar em má qualidade. O texto pode ser difícil de ler e detalhes finos podem ser perdidos.",
        highFilesizeWarning: "Aviso: DPI alto resultará em arquivos maiores. O processamento também pode demorar mais.",
        highComputeWarning: "Aviso: O processamento acima de 600 DPI é intensivo computacionalmente. Seu dispositivo pode esquentar, ficar lento ou ficar sem memória. Esta configuração de DPI alto normalmente só é necessária ao converter PDFs para um formato básico para contornar problemas de impressão com caracteres acentuados ou não latinos.",
        resultSaveButton: "Salvar o PDF resultante",
        resultRecommendIgnore: "Para este PDF em particular, recomendamos usar seu PDF original e ignorar este aplicativo.",
        resultDidntCompressWell: " O PDF não comprimiu bem.",
        resultBecameBigger: " O PDF ficou maior.",
        resultAppPurpose: "Este aplicativo é melhor usado com documentos digitalizados com aparência de alto contraste em preto e branco (você precisa usar outro aplicativo para digitalizar). Se o PDF já estava bem otimizado, este aplicativo não pode ajudar. Este aplicativo existe apenas porque a maioria dos aplicativos de scanner PDF disponíveis salva o resultado de boa aparência com compressão JPEG ineficiente em vez da eficiente compressão CCITT G4.",
        resultDitheringNote: "O pontilhamento piora a compressão, mas às vezes é necessário para gráficos ou texto de baixo contraste.",
        resultDitheringAdvice: " Considere não usar pontilhamento, ou usar pontilhamento apenas em páginas selecionadas, por exemplo, onde há gráficos. O texto geralmente é melhor sem pontilhamento.",
    },

    // Czech
    cs: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF snížením barev na jednobitovou černobílou, úpravou DPI rozlišení a použitím efektivní CCITT Group 4 komprese (ITU-T T.6, MMR nebo Fax komprese).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zařízení.",
        chooseFile: "Vybrat PDF soubor",
        conversionMode: "Režim převodu:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylem (Hladké)",
        ditherSelected: "Rozptýlit pouze vybrané stránky",
        pageRangePlaceholder: "např. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadejte čísla stránek a rozsahy oddělené čárkami",
        pageSize: "Velikost stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šířku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šířku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupní DPI (Rozlišení):",
        dpiStandard: "Standardní (310 DPI)",
        dpiCustom: "Vlastní DPI",
        dpiHint: "Vyšší DPI = větší soubor, ale lepší kvalita. Doporučeno 310 DPI.",
        compressButton: "Komprimovat do G4",
        processing: "Zpracovávání...",
        credits: "Vytvořeno s PDF.js • pako • G4Enc",
        license: "Licencováno pod Apache 2.0 • Zobrazit licence a uvedení autorů",
        about: "O tomto projektu • Studie pochybných rozhodnutí",        lowQualityWarning: "Varování: Nízké DPI může vést ke špatné kvalitě. Text může být obtížně čitelný a jemné detaily mohou být ztraceny.",
        highFilesizeWarning: "Varování: Vysoké DPI povede k větším souborům. Zpracování může také trvat déle.",
        highComputeWarning: "Varování: Zpracování nad 600 DPI je výpočetně náročné. Vaše zařízení se může zahřát, zpomalit nebo dojít paměť. Toto vysoké nastavení DPI je obvykle potřeba pouze při převodu PDF do základního formátu pro obejití problémů s tiskem u akcentovaných nebo ne-latinských znaků.",
        resultSaveButton: "Uložit výsledné PDF",
        resultRecommendIgnore: "Pro tento konkrétní PDF doporučujeme použít váš původní PDF a tuto aplikaci ignorovat.",
        resultDidntCompressWell: " PDF se dobře nekomprimovalo.",
        resultBecameBigger: " PDF se zvětšilo.",
        resultAppPurpose: "Tato aplikace se nejlépe používá se skenovanými dokumenty s kontrastním černobílým vzhledem (musíte použít jinou aplikaci pro skenování). Pokud byl PDF již dobře optimalizován, tato aplikace nemůže pomoci. Tato aplikace existuje pouze proto, že většina dostupných aplikací pro skenování PDF ukládá pěkně vypadající výsledek s neefektivní kompresí JPEG místo efektivní komprese CCITT G4.",
        resultDitheringNote: "Rozptyl zhoršuje kompresi, ale někdy je nutný pro grafiku nebo text s nízkým kontrastem.",
        resultDitheringAdvice: " Zvažte nepoužívání rozptylu nebo použití rozptylu pouze na vybraných stránkách, např. kde jsou grafiky. Text je obvykle nejlepší bez rozptylu.",
    },

    // Slovak
    sk: {
        title: "PDF Monochromatický G4 Kompresor",
        subtitle: "Komprimujte PDF znížením farieb na jednobitovú čiernobielu, úpravou DPI rozlíšenia a použitím efektívnej CCITT Group 4 kompresie (ITU-T T.6, MMR alebo Fax kompresia).",        privacyNotice: "🔒 Funguje 100% offline. Vaše PDF nikdy neopustí vaše zariadenie.",
        chooseFile: "Vybrať PDF súbor",
        conversionMode: "Režim konverzie:",
        noDither: "Bez rozptylu (Ostré)",
        dither: "S rozptylom (Hladké)",
        ditherSelected: "Rozptyliť len vybrané strany",
        pageRangePlaceholder: "napr. 1, 3-5, 8, 10-12",
        pageRangeHint: "Zadajte čísla strán a rozsahy oddelené čiarkami",
        pageSize: "Veľkosť stránky:",
        pageSizeA4Portrait: "A4 Na výšku",
        pageSizeA4Landscape: "A4 Na šírku",
        pageSizeLetterPortrait: "Letter Na výšku",
        pageSizeLetterLandscape: "Letter Na šírku",
        pageSizeLegalPortrait: "US Legal Na výšku",
        outputDpi: "Výstupné DPI (Rozlíšenie):",
        dpiStandard: "Štandardné (310 DPI)",
        dpiCustom: "Vlastné DPI",
        dpiHint: "Vyššie DPI = väčší súbor, ale lepšia kvalita. Odporúčané 310 DPI.",
        compressButton: "Komprimovať do G4",
        processing: "Spracovávanie...",
        credits: "Vytvorené s PDF.js • pako • G4Enc",
        license: "Licencované pod Apache 2.0 • Zobraziť licencie a uvedenie autorov",
        about: "O tomto projekte • Štúdia pochybných rozhodnutí",        lowQualityWarning: "Varovanie: Nízke DPI môže viesť k zlej kvalite. Text môže byť ťažko čitateľný a jemné detaily môžu byť stratené.",
        highFilesizeWarning: "Varovanie: Vysoké DPI povedie k väčším súborom. Spracovanie môže tiež trvať dlhšie.",
        highComputeWarning: "Varovanie: Spracovanie nad 600 DPI je výpočtovo náročné. Vaše zariadenie sa môže zahriať, spomaliť alebo dôjsť pamäť. Toto vysoké nastavenie DPI je zvyčajne potrebné len pri prevode PDF do základného formátu pre obídenie problémov s tlačou u akcentovaných alebo ne-latinských znakov.",
        resultSaveButton: "Uložiť výsledné PDF",
        resultRecommendIgnore: "Pre tento konkrétny PDF odporúčame použiť váš pôvodný PDF a túto aplikáciu ignorovať.",
        resultDidntCompressWell: " PDF sa dobre nekomprimovalo.",
        resultBecameBigger: " PDF sa zväčšilo.",
        resultAppPurpose: "Táto aplikácia sa najlepšie používa so skenovanými dokumentmi s kontrastným čierno-bielym vzhľadom (musíte použiť inú aplikáciu na skenovanie). Ak bol PDF už dobre optimalizovaný, táto aplikácia nemôže pomôcť. Táto aplikácia existuje len preto, že väčšina dostupných aplikácií pre skenovanie PDF ukladá pekne vyzerajúci výsledok s neefektívnou kompresiou JPEG namiesto efektívnej kompresie CCITT G4.",
        resultDitheringNote: "Rozptyl zhoršuje kompresiu, ale niekedy je nutný pre grafiku alebo text s nízkym kontrastom.",
        resultDitheringAdvice: " Zvážte nepoužívanie rozptylu alebo použitie rozptylu len na vybraných stránkach, napr. kde sú grafiky. Text je zvyčajne najlepší bez rozptylu.",
    },

    // Continue in next file due to length...
};

// Language detection with regional fallback
function detectLanguage() {
    // Get browser language(s)
    const languages = navigator.languages || [navigator.language || navigator.userLanguage || 'en'];

    for (let locale of languages) {
        locale = locale.toLowerCase();

        // Try exact match first
        if (TRANSLATIONS[locale]) {
            return locale;
        }

        // Try with fallback map
        if (LOCALE_FALLBACK[locale] && TRANSLATIONS[LOCALE_FALLBACK[locale]]) {
            return LOCALE_FALLBACK[locale];
        }

        // Try base language (en-US → en)
        const baseLang = locale.split('-')[0];
        if (TRANSLATIONS[baseLang]) {
            return baseLang;
        }
    }

    // Default to English
    return 'en';
}

// Apply translations
function applyTranslations(lang) {
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;

    // Set RTL direction
    if (RTL_LANGUAGES.has(lang)) {
        document.body.setAttribute('dir', 'rtl');
    } else {
        document.body.setAttribute('dir', 'ltr');
    }

    // Translate all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (t[key]) {
            if (element.tagName === 'INPUT' && element.type === 'text') {
                element.placeholder = t[key];
            } else {
                element.textContent = t[key];
            }
        }
    });

    // Handle parameterized strings (like DPI dimensions)
    document.querySelectorAll('[data-i18n-template]').forEach(element => {
        const key = element.getAttribute('data-i18n-template');
        if (t[key]) {
            element.setAttribute('data-i18n-template-text', t[key]);
        }
    });
}
