#!/usr/bin/env python3
"""
JBIG2 to PDF/A-1B Converter
Takes jbig2enc output (global symbol dictionary + page segments) and wraps in PDF/A
No external dependencies

Generated by Claude AI

Copyright 2026 PDF Monochrome CCITT G4 Compressor Contributors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

================================================================================
ATTRIBUTIONS AND CODE PROVENANCE
================================================================================

This code incorporates knowledge gained from studying open-source projects,
but all implementations are original unless explicitly noted.

1. jbig2enc - JBIG2 Encoder
   Author: Adam Langley (agl@imperialviolet.org)
   URL: https://github.com/agl/jbig2enc
   License: Apache License 2.0
   Copyright: (C) 2006 Google Inc.

   What we learned by studying jbig2enc/jbig2topdf.py:
   - Concept: How jbig2enc outputs files (*.sym for global dictionary, *.0000, *.0001 for pages)
   - Concept: How to embed JBIG2 streams in PDF XObjects using /JBIG2Decode filter
   - Concept: How to reference global symbol dictionary via /JBIG2Globals in DecodeParms

   What we DID NOT do:
   - We did NOT copy source code from jbig2topdf.py
   - We studied its approach and wrote our own implementation
   - Our PDF/A structure is adapted from our own tiff2pdf_img2pdf.py

2. JBIG2 Specification (ITU-T T.88)
   - Public domain specification
   - Used for implementing JBIG2 segment header parsing
   - Defines segment types, file format, page information segments

3. tiff2pdf_img2pdf.py (this project)
   - Our own code (see that file for its attributions)
   - PDF/A-1B structure, XMP metadata, CalGray colorspace all from there
   - This file adapts that approach for JBIG2 instead of CCITT

================================================================================
"""

import struct
import sys
import os
import glob

# ============================================================================
# JBIG2 Segment Parser
# ORIGINAL: Based on JBIG2 Specification (ITU-T T.88)
# Parses JBIG2 file format to extract page dimensions from page info segments
# ============================================================================
def read_jbig2_metadata(jbig2_data):
    """
    Parse JBIG2 file header to extract page dimensions.
    JBIG2 file organization flag in first segment tells us if it's sequential or random-access.

    ORIGINAL implementation based on ITU-T T.88 specification.
    """
    if len(jbig2_data) < 13:
        return None, None

    # JBIG2 file header (if present): 8 bytes magic + 1 byte flags
    # Magic: 0x97 0x4A 0x42 0x32 0x0D 0x0A 0x1A 0x0A (JBIG2 with line endings)
    if jbig2_data[:8] == b'\x97\x4a\x42\x32\x0d\x0a\x1a\x0a':
        # File has header - skip it (13 bytes total: 8 magic + 1 flags + 4 page count)
        offset = 13
    else:
        offset = 0

    # Read segments to find page information segment (type 48 or 49)
    width = height = None
    while offset < len(jbig2_data) - 11:
        if offset + 5 > len(jbig2_data):
            break

        # Segment header structure:
        # 4 bytes: segment number
        # 1 byte: flags
        # variable: referenced segment count (1 byte if count <= 4, else more)
        # 1 or 4 bytes: page association
        # 4 bytes: data length
        # N bytes: segment data

        seg_num = struct.unpack('>I', jbig2_data[offset:offset+4])[0]
        flags = jbig2_data[offset+4]
        seg_type = flags & 0x3f

        offset += 5

        # Read referenced segment count
        if offset >= len(jbig2_data):
            break
        ref_seg_count_byte = jbig2_data[offset]
        offset += 1

        # Referenced segment count encoding
        if (ref_seg_count_byte >> 5) == 7:
            # Long form - next 4 bytes contain count
            if offset + 4 > len(jbig2_data):
                break
            ref_count = struct.unpack('>I', jbig2_data[offset:offset+4])[0] & 0x1fffffff
            offset += 4
        else:
            # Short form - count is in first 3 bits
            ref_count = ref_seg_count_byte >> 5

        # Skip referenced segment numbers (4 bytes each if seg_num > 256, else 1 byte each)
        if seg_num > 256:
            offset += ref_count * 4
        else:
            offset += ref_count

        # Skip retention flags if ref_count > 0
        if ref_count > 0:
            retention_bytes = (ref_count + 7) // 8
            offset += retention_bytes

        # Page association field size
        page_assoc_size = 1 if (flags & 0x40) else 4
        offset += page_assoc_size

        if offset + 4 > len(jbig2_data):
            break

        # Data length
        data_length = struct.unpack('>I', jbig2_data[offset:offset+4])[0]
        offset += 4

        # Page information segment (type 48 = intermediate, 49 = end)
        if seg_type == 48 or seg_type == 49:
            if offset + 8 <= len(jbig2_data):
                width = struct.unpack('>I', jbig2_data[offset:offset+4])[0]
                height = struct.unpack('>I', jbig2_data[offset+4:offset+8])[0]
                break

        offset += data_length

    return width, height

# ============================================================================
# PBM Header Parser
# ORIGINAL: Simple PBM (Portable Bitmap) P4 format header parser
# ============================================================================
def read_pbm_dimensions(pbm_path):
    """Read width and height from a PBM file header.

    ORIGINAL implementation - PBM format is trivial (magic + dimensions).
    """
    try:
        with open(pbm_path, 'rb') as f:
            # Read magic (P4 for binary PBM)
            magic = f.readline().decode('ascii').strip()
            if magic != 'P4':
                return None, None

            # Skip comments
            line = f.readline().decode('ascii').strip()
            while line.startswith('#'):
                line = f.readline().decode('ascii').strip()

            # Parse width and height
            parts = line.split()
            if len(parts) >= 2:
                width = int(parts[0])
                height = int(parts[1])
                return width, height
    except:
        pass
    return None, None

# ============================================================================
# PDF/A-1B Creation with JBIG2 Compression
# ADAPTED from tiff2pdf_img2pdf.py (this project)
# JBIG2-specific parts studied from jbig2enc/jbig2topdf.py (Apache-2.0)
# ============================================================================
def create_jbig2_pdf(jbig2_prefix, output_path):
    """
    Create PDF/A-1B from jbig2enc output files.
    jbig2enc with -s -p creates:
      - prefix.sym (global symbol dictionary)
      - prefix.0000, prefix.0001, ... (page segments)

    File format learned from jbig2enc/jbig2topdf.py.
    PDF/A structure adapted from tiff2pdf_img2pdf.py.
    """
    # Find all page segments
    page_files = sorted(glob.glob(f"{jbig2_prefix}.[0-9][0-9][0-9][0-9]"))
    if not page_files:
        print(f"Error: No JBIG2 page files found for prefix {jbig2_prefix}")
        sys.exit(1)

    # Read global symbol dictionary if present
    # File naming convention from jbig2enc: prefix.sym, prefix.0000, prefix.0001, ...
    global_data = None
    sym_file = f"{jbig2_prefix}.sym"
    if os.path.exists(sym_file):
        with open(sym_file, 'rb') as f:
            global_data = f.read()

    # Determine dimensions from source PBM files
    # The jbig2_prefix is like "tmp_jbig2_12345/output", so get the directory
    jbig2_dir = os.path.dirname(jbig2_prefix)
    jbig2_base = os.path.basename(jbig2_prefix)

    # Determine PBM prefix (output -> page, dither-output -> dither-page)
    if 'dither' in jbig2_base:
        pbm_prefix = 'dither-page'
    else:
        pbm_prefix = 'page'

    # Read all pages and extract metadata
    pages = []
    for i, page_file in enumerate(page_files):
        with open(page_file, 'rb') as f:
            page_data = f.read()

        # Get dimensions from corresponding PBM file
        pbm_file = os.path.join(jbig2_dir, f"{pbm_prefix}-{i:04d}.pbm")
        width, height = read_pbm_dimensions(pbm_file)

        # Fallback: A4 at 310 DPI (our standard from GM conversion)
        if width is None or height is None:
            # A4 portrait: 210mm x 297mm at 310 DPI
            width = int(210 / 25.4 * 310)   # ~2551 pixels
            height = int(297 / 25.4 * 310)  # ~3622 pixels

        pages.append({
            'width': width,
            'height': height,
            'data': page_data
        })

    if not pages:
        print("Error: No valid pages found")
        sys.exit(1)

    # Create PDF/A-1B
    pdf = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"

    # A4 portrait in points
    page_width_pt = 595
    page_height_pt = 842

    objects = []
    obj_num = 1

    # ORIGINAL: CalGray color space (PDF/A compliant, from tiff2pdf_img2pdf.py)
    # D65 white point, Gamma 1.0 for neutral rendering (no gamma curve applied to whites)
    calgray_colorspace = "[/CalGray << /WhitePoint [0.9505 1.0000 1.0890] /Gamma 1.0 >>]"

    # ========================================================================
    # Global JBIG2 dictionary stream (if present)
    # Referenced by all page images via DecodeParms
    # Concept from jbig2enc/jbig2topdf.py: global symbol dictionary reduces
    # file size by sharing common symbols across pages
    # ========================================================================
    global_obj_num = None
    if global_data:
        global_obj_num = obj_num
        obj_num += 1

        global_obj = (
            f"<< /Length {len(global_data)} >>".encode() +
            b"\nstream\n" + global_data + b"\nendstream"
        )
        objects.append(global_obj)

    # Create image and content objects for each page
    page_obj_nums = []
    for i, page in enumerate(pages):
        # ====================================================================
        # Image XObject - JBIG2Decode
        # Concept from jbig2enc/jbig2topdf.py: Use /JBIG2Decode filter
        # DecodeParms with /JBIG2Globals references the global dictionary
        # ====================================================================
        img_obj_num = obj_num
        obj_num += 1

        data_length = len(page['data'])

        # Build DecodeParms
        # Concept from jbig2enc/jbig2topdf.py and JBIG2 spec:
        # /JBIG2Globals references the shared symbol dictionary
        if global_obj_num:
            # Reference global symbol dictionary
            decode_parms = f"<< /JBIG2Globals {global_obj_num} 0 R >>"
        else:
            # No global dictionary
            decode_parms = "<< >>"

        img_dict = (
            f"<< /Type /XObject "
            f"/Subtype /Image "
            f"/Width {page['width']} "
            f"/Height {page['height']} "
            f"/ColorSpace {calgray_colorspace} "
            f"/BitsPerComponent 1 "
            f"/Filter /JBIG2Decode "
            f"/DecodeParms {decode_parms} "
            f"/Decode [0 1] "  # Explicit: sample 0→black (0.0), sample 1→white (1.0)
            f"/Length {data_length} >>"
        ).encode()

        img_obj = img_dict + b"\nstream\n" + page['data'] + b"\nendstream"
        objects.append(img_obj)

        # ====================================================================
        # Content Stream - A4 scaling and centering
        # ORIGINAL: From tiff2pdf_img2pdf.py - same logic
        # ====================================================================
        content_obj_num = obj_num
        obj_num += 1

        # Calculate aspect ratios and scale to fit A4
        img_aspect = page['width'] / page['height']
        page_aspect = page_width_pt / page_height_pt

        if img_aspect > page_aspect:
            scale = page_width_pt / page['width']
        else:
            scale = page_height_pt / page['height']

        scaled_width = page['width'] * scale
        scaled_height = page['height'] * scale

        # Center image on A4 page
        x_offset = (page_width_pt - scaled_width) / 2
        y_offset = (page_height_pt - scaled_height) / 2

        content_stream = (
            f"q\n{scaled_width:.4f} 0 0 {scaled_height:.4f} {x_offset:.4f} {y_offset:.4f} cm\n/Im{i} Do\nQ\n"
        ).encode()

        content_obj = (
            f"<< /Length {len(content_stream)} >>".encode() +
            b"\nstream\n" + content_stream + b"\nendstream"
        )
        objects.append(content_obj)

        # ====================================================================
        # Page object
        # ====================================================================
        page_obj_num = obj_num
        obj_num += 1
        page_obj_nums.append(page_obj_num)

        page_obj = (
            f"<< /Type /Page /Parent {obj_num} 0 R "
            f"/MediaBox [0 0 {page_width_pt} {page_height_pt}] "
            f"/Resources << /XObject << /Im{i} {img_obj_num} 0 R >> >> "
            f"/Contents {content_obj_num} 0 R >>"
        ).encode()
        objects.append(page_obj)

    # ========================================================================
    # Pages object
    # ========================================================================
    pages_obj_num = obj_num
    obj_num += 1

    kids = ' '.join([f"{n} 0 R" for n in page_obj_nums])
    pages_obj = (
        f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>"
    ).encode()
    objects.append(pages_obj)

    # ========================================================================
    # XMP Metadata stream - PDF/A-1B requirement
    # ORIGINAL: From tiff2pdf_img2pdf.py - same structure
    # ========================================================================
    metadata_obj_num = obj_num
    obj_num += 1

    import datetime
    now = datetime.datetime.now(datetime.timezone.utc)
    timestamp = now.strftime('%Y-%m-%dT%H:%M:%S+00:00')

    xmp_metadata = f'''<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:format>application/pdf</dc:format>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">
      <pdfaid:part>1</pdfaid:part>
      <pdfaid:conformance>B</pdfaid:conformance>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
      <xmp:CreateDate>{timestamp}</xmp:CreateDate>
      <xmp:ModifyDate>{timestamp}</xmp:ModifyDate>
      <xmp:MetadataDate>{timestamp}</xmp:MetadataDate>
      <xmp:CreatorTool>jbig2pdf.py</xmp:CreatorTool>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
      <pdf:Producer>jbig2pdf.py</pdf:Producer>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>'''.encode('utf-8')

    metadata_obj = (
        f"<< /Type /Metadata /Subtype /XML /Length {len(xmp_metadata)} >>".encode() +
        b"\nstream\n" + xmp_metadata + b"\nendstream"
    )
    objects.append(metadata_obj)

    # ========================================================================
    # OutputIntent - PDF/A-1B requirement
    # ORIGINAL: From tiff2pdf_img2pdf.py
    # ========================================================================
    output_intent_obj_num = obj_num
    obj_num += 1

    output_intent_obj = (
        f"<< /Type /OutputIntent "
        f"/S /GTS_PDFA1 "
        f"/OutputConditionIdentifier (Gray Gamma 2.2) "
        f"/Info (Grayscale with Gamma 2.2) >>"
    ).encode()
    objects.append(output_intent_obj)

    # ========================================================================
    # Catalog
    # ORIGINAL: From tiff2pdf_img2pdf.py - PDF/A compliance
    # ========================================================================
    catalog_obj_num = obj_num
    obj_num += 1

    catalog_obj = (
        f"<< /Type /Catalog /Pages {pages_obj_num} 0 R "
        f"/Metadata {metadata_obj_num} 0 R "
        f"/OutputIntents [{output_intent_obj_num} 0 R] "
        f"/MarkInfo << /Marked true >> "
        f"/ViewerPreferences << /DisplayDocTitle true >> >>"
    ).encode()
    objects.append(catalog_obj)

    # ========================================================================
    # Write PDF structure
    # ========================================================================
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"

    # Write xref table
    xref_offset = len(pdf)
    pdf += b"xref\n"
    pdf += f"0 {len(objects) + 1}\n".encode()
    pdf += b"0000000000 65535 f \n"
    for offset in offsets:
        pdf += f"{offset:010d} 00000 n \n".encode()

    # ========================================================================
    # Trailer with ID array
    # ORIGINAL: From tiff2pdf_img2pdf.py - PDF/A requirement
    # ========================================================================
    import hashlib
    import time

    id_source = f"{output_path}{time.time()}{len(pages)}".encode()
    file_id = hashlib.md5(id_source).hexdigest().upper()

    pdf += b"trailer\n"
    pdf += (
        f"<< /Size {len(objects) + 1} "
        f"/Root {catalog_obj_num} 0 R "
        f"/ID [<{file_id}> <{file_id}>] >>\n"
    ).encode()
    pdf += b"startxref\n"
    pdf += f"{xref_offset}\n".encode()
    pdf += b"%%EOF\n"

    with open(output_path, 'wb') as f:
        f.write(pdf)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: jbig2pdf.py <jbig2_prefix> <output.pdf>")
        print("  Expects jbig2enc output: prefix.sym, prefix.0000, prefix.0001, ...")
        sys.exit(1)

    jbig2_prefix = sys.argv[1]
    output_file = sys.argv[2]

    try:
        create_jbig2_pdf(jbig2_prefix, output_file)
        # Count pages
        page_count = len(glob.glob(f"{jbig2_prefix}.[0-9][0-9][0-9][0-9]"))
        print(f"Successfully created {output_file} with {page_count} page(s)")
    except Exception as e:
        print(f"Error creating PDF: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
