#!/usr/bin/env python3
"""
PDF Stream Compressor
Applies FlateDecode compression to all streams in a PDF
Cascades FlateDecode on top of existing filters (like CCITTFaxDecode)

Generated by Claude AI

Copyright 2026 PDF Monochrome CCITT G4 Compressor Contributors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

No external dependencies - uses only Python stdlib
Designed for PDFs created by tiff2pdf_img2pdf.py or jbig2pdf.py

All code in this file is original implementation.
"""

import sys
import zlib
import re

def find_objects(pdf_data):
    """Find all objects in PDF and their positions."""
    # Pattern: "N 0 obj" where N is object number
    pattern = rb'(\d+) 0 obj\s*'
    objects = []

    for match in re.finditer(pattern, pdf_data):
        obj_num = int(match.group(1))
        start = match.end()

        # Find corresponding endobj
        endobj_pattern = rb'endobj'
        endobj_match = re.search(endobj_pattern, pdf_data[start:])
        if endobj_match:
            end = start + endobj_match.start()
            objects.append({
                'num': obj_num,
                'start': start,
                'end': end,
                'data': pdf_data[start:end]
            })

    return objects

def parse_stream_object(obj_data):
    """Parse a stream object to extract dictionary and stream data."""
    # Look for stream/endstream markers
    stream_match = re.search(rb'stream\s*\n', obj_data)
    if not stream_match:
        return None, None, None

    dict_data = obj_data[:stream_match.start()]
    stream_start = stream_match.end()

    endstream_match = re.search(rb'\s*endstream', obj_data[stream_start:])
    if not endstream_match:
        return None, None, None

    stream_data = obj_data[stream_start:stream_start + endstream_match.start()]

    return dict_data, stream_data, obj_data[stream_start + endstream_match.end():]

def parse_dict(dict_data):
    """Simple dictionary parser - extracts key-value pairs."""
    dict_str = dict_data.decode('latin-1', errors='ignore')

    # Extract /Length value
    length_match = re.search(r'/Length\s+(\d+)', dict_str)
    length = int(length_match.group(1)) if length_match else None

    # Extract /Filter value
    filter_match = re.search(r'/Filter\s+(/\w+|\[[^\]]+\])', dict_str)
    current_filter = filter_match.group(1) if filter_match else None

    return {
        'length': length,
        'filter': current_filter,
        'raw': dict_data
    }

def update_dict_with_compression(dict_data, new_length, cascade_filter=None):
    """Update dictionary with new length and optionally cascade filters."""
    dict_str = dict_data.decode('latin-1', errors='ignore')

    # Update /Length
    dict_str = re.sub(r'/Length\s+\d+', f'/Length {new_length}', dict_str)

    # Update /Filter and /DecodeParms
    if cascade_filter:
        if '/Filter' in dict_str:
            # Already has a filter - create cascaded filter array
            # Find the existing filter
            filter_match = re.search(r'/Filter\s+(/\w+)', dict_str)
            if filter_match:
                existing_filter = filter_match.group(1)

                # Check if there's a DecodeParms
                decode_parms_match = re.search(r'/DecodeParms\s+(<<[^>]+>>)', dict_str)

                if decode_parms_match:
                    # Has DecodeParms - create array for both
                    existing_decode_parms = decode_parms_match.group(1)

                    # Replace Filter
                    dict_str = re.sub(
                        r'/Filter\s+/\w+',
                        f'/Filter [ /FlateDecode {existing_filter} ]',
                        dict_str
                    )

                    # Replace DecodeParms with array: [ null <existing> ]
                    # FlateDecode doesn't need params, CCITTFaxDecode/JBIG2Decode needs the original
                    dict_str = re.sub(
                        r'/DecodeParms\s+<<[^>]+>>',
                        f'/DecodeParms [ null {existing_decode_parms} ]',
                        dict_str
                    )
                else:
                    # No DecodeParms - just add filter
                    dict_str = re.sub(
                        r'/Filter\s+/\w+',
                        f'/Filter [ /FlateDecode {existing_filter} ]',
                        dict_str
                    )
        else:
            # No filter - add FlateDecode
            # Insert before /Length
            dict_str = re.sub(
                r'(/Length)',
                r'/Filter /FlateDecode \1',
                dict_str
            )

    return dict_str.encode('latin-1')

def compress_pdf_streams(input_pdf, output_pdf):
    """Compress all streams in a PDF file."""
    print(f"Reading {input_pdf}...")

    with open(input_pdf, 'rb') as f:
        pdf_data = f.read()

    # Find PDF header
    header_end = pdf_data.find(b'\n', 20)  # After %PDF-1.4 and binary marker
    header = pdf_data[:header_end + 1]

    # Find xref position
    xref_match = re.search(rb'xref\s*\n', pdf_data)
    if not xref_match:
        print("Error: Could not find xref table")
        return False

    xref_start = xref_match.start()

    # Parse objects
    print("Parsing PDF objects...")
    objects = find_objects(pdf_data[:xref_start])
    print(f"Found {len(objects)} objects")

    # Process each object
    compressed_objects = []
    compression_stats = {'compressed': 0, 'cascaded': 0, 'skipped': 0}

    for obj in objects:
        dict_part, stream_data, trailing = parse_stream_object(obj['data'])

        if stream_data is None:
            # Not a stream object - keep as-is
            compressed_objects.append(obj['data'])
            compression_stats['skipped'] += 1
            continue

        # Parse dictionary
        dict_info = parse_dict(dict_part)

        # Compress stream data
        original_size = len(stream_data)
        compressed_data = zlib.compress(stream_data, level=9)
        compressed_size = len(compressed_data)

        # Determine if we're cascading
        has_existing_filter = dict_info['filter'] is not None

        # Update dictionary
        new_dict = update_dict_with_compression(
            dict_part,
            compressed_size,
            cascade_filter=True  # Always add FlateDecode
        )

        # Rebuild object
        new_obj = new_dict + b'\nstream\n' + compressed_data + b'\nendstream'
        compressed_objects.append(new_obj)

        if has_existing_filter:
            compression_stats['cascaded'] += 1
            print(f"  Object {obj['num']}: {original_size} -> {compressed_size} bytes (cascaded with {dict_info['filter']})")
        else:
            compression_stats['compressed'] += 1
            print(f"  Object {obj['num']}: {original_size} -> {compressed_size} bytes (FlateDecode)")

    # Rebuild PDF
    print("\nRebuilding PDF...")
    new_pdf = header
    offsets = []

    for i, obj_data in enumerate(compressed_objects, start=1):
        offsets.append(len(new_pdf))
        new_pdf += f"{i} 0 obj\n".encode('latin-1')
        new_pdf += obj_data
        new_pdf += b"\nendobj\n"

    # Write xref table
    xref_offset = len(new_pdf)
    new_pdf += b"xref\n"
    new_pdf += f"0 {len(compressed_objects) + 1}\n".encode('latin-1')
    new_pdf += b"0000000000 65535 f \n"
    for offset in offsets:
        new_pdf += f"{offset:010d} 00000 n \n".encode('latin-1')

    # Copy trailer from original PDF
    trailer_match = re.search(rb'trailer\s*\n(.*?)startxref', pdf_data, re.DOTALL)
    if trailer_match:
        trailer_dict = trailer_match.group(1)
        new_pdf += b"trailer\n"
        new_pdf += trailer_dict
        new_pdf += b"startxref\n"
        new_pdf += f"{xref_offset}\n".encode('latin-1')
        new_pdf += b"%%EOF\n"
    else:
        print("Warning: Could not find original trailer")
        return False

    # Write output
    print(f"\nWriting {output_pdf}...")
    with open(output_pdf, 'wb') as f:
        f.write(new_pdf)

    # Stats
    original_size = len(pdf_data)
    new_size = len(new_pdf)
    reduction = ((original_size - new_size) / original_size) * 100

    print(f"\n=== Compression Statistics ===")
    print(f"Objects with new compression: {compression_stats['compressed']}")
    print(f"Objects with cascaded compression: {compression_stats['cascaded']}")
    print(f"Objects unchanged: {compression_stats['skipped']}")
    print(f"\nOriginal size: {original_size:,} bytes")
    print(f"Compressed size: {new_size:,} bytes")
    print(f"Reduction: {reduction:.2f}%")

    return True

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: pdf_compress.py input.pdf output.pdf")
        print("  Applies FlateDecode compression to all streams in a PDF")
        print("  Cascades with existing filters (CCITT, JBIG2, etc.)")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    try:
        success = compress_pdf_streams(input_file, output_file)
        if success:
            print("\n✓ Compression complete!")
        else:
            print("\n✗ Compression failed")
            sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
