#!/usr/bin/env python3
"""
TIFF to PDF/A-1B Converter
Handles CCITT Group 4 compressed TIFFs without re-encoding

Generated by Claude AI

Copyright 2026 PDF Monochrome CCITT G4 Compressor Contributors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

================================================================================
ATTRIBUTIONS AND CODE PROVENANCE
================================================================================

This code incorporates knowledge gained from studying open-source projects,
but all implementations are original unless explicitly noted.

1. img2pdf - Lossless Image to PDF Converter
   Author: Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>
   URL: https://gitlab.mister-muffin.de/josch/img2pdf
   License: GNU Lesser General Public License v3+
   Copyright: (C) 2012-2021 Johannes Schauer Marin Rodrigues

   What we learned by studying img2pdf:
   - Concept: How FillOrder tag affects bit order in TIFF data
   - Concept: How to set BlackIs1 based on photometric interpretation
   - Concept: General approach to embedding CCITT streams in PDF XObjects
   - Concept: DecodeParms structure for CCITT compression

   What we DID NOT do:
   - We did NOT copy source code from img2pdf
   - We studied its approach and wrote our own implementation
   - All code in this file is original or from other sources (see below)

2. libtiff - TIFF Software Library
   URL: https://gitlab.com/libtiff/libtiff
   License: LibTIFF License (BSD-style, permissive - see LICENSES.md)
   Copyright: © 1988-1997 Sam Leffler, © 1991-1997 Silicon Graphics, Inc.

   What we used:
   - TIFFBitRevTable: Standard bit reversal lookup table (see below)
   - This is a well-known constant array used across many TIFF implementations

3. TIFF 6.0 Specification
   - Public domain specification
   - Used for implementing TIFF IFD parsing

================================================================================
"""
import struct
import sys
import os

# ============================================================================
# TIFFBitRevTable - Bit Reversal Lookup Table
# SOURCE: libtiff (tiff2pdf.c, tif_swab.c)
# LICENSE: LibTIFF License (BSD-style, permissive - see LICENSES.md)
# COPYRIGHT: © 1988-1997 Sam Leffler, © 1991-1997 Silicon Graphics, Inc.
#
# This table reverses the bit order in a byte (MSB ↔ LSB).
# Used to handle TIFF FillOrder tag when set to LSB2MSB (value 2).
# This is a well-known constant array used in many TIFF implementations.
# ============================================================================
TIFFBitRevTable = [
    0x00, 0x80, 0x40, 0xC0, 0x20, 0xA0, 0x60, 0xE0,
    0x10, 0x90, 0x50, 0xD0, 0x30, 0xB0, 0x70, 0xF0,
    0x08, 0x88, 0x48, 0xC8, 0x28, 0xA8, 0x68, 0xE8,
    0x18, 0x98, 0x58, 0xD8, 0x38, 0xB8, 0x78, 0xF8,
    0x04, 0x84, 0x44, 0xC4, 0x24, 0xA4, 0x64, 0xE4,
    0x14, 0x94, 0x54, 0xD4, 0x34, 0xB4, 0x74, 0xF4,
    0x0C, 0x8C, 0x4C, 0xCC, 0x2C, 0xAC, 0x6C, 0xEC,
    0x1C, 0x9C, 0x5C, 0xDC, 0x3C, 0xBC, 0x7C, 0xFC,
    0x02, 0x82, 0x42, 0xC2, 0x22, 0xA2, 0x62, 0xE2,
    0x12, 0x92, 0x52, 0xD2, 0x32, 0xB2, 0x72, 0xF2,
    0x0A, 0x8A, 0x4A, 0xCA, 0x2A, 0xAA, 0x6A, 0xEA,
    0x1A, 0x9A, 0x5A, 0xDA, 0x3A, 0xBA, 0x7A, 0xFA,
    0x06, 0x86, 0x46, 0xC6, 0x26, 0xA6, 0x66, 0xE6,
    0x16, 0x96, 0x56, 0xD6, 0x36, 0xB6, 0x76, 0xF6,
    0x0E, 0x8E, 0x4E, 0xCE, 0x2E, 0xAE, 0x6E, 0xEE,
    0x1E, 0x9E, 0x5E, 0xDE, 0x3E, 0xBE, 0x7E, 0xFE,
    0x01, 0x81, 0x41, 0xC1, 0x21, 0xA1, 0x61, 0xE1,
    0x11, 0x91, 0x51, 0xD1, 0x31, 0xB1, 0x71, 0xF1,
    0x09, 0x89, 0x49, 0xC9, 0x29, 0xA9, 0x69, 0xE9,
    0x19, 0x99, 0x59, 0xD9, 0x39, 0xB9, 0x79, 0xF9,
    0x05, 0x85, 0x45, 0xC5, 0x25, 0xA5, 0x65, 0xE5,
    0x15, 0x95, 0x55, 0xD5, 0x35, 0xB5, 0x75, 0xF5,
    0x0D, 0x8D, 0x4D, 0xCD, 0x2D, 0xAD, 0x6D, 0xED,
    0x1D, 0x9D, 0x5D, 0xDD, 0x3D, 0xBD, 0x7D, 0xFD,
    0x03, 0x83, 0x43, 0xC3, 0x23, 0xA3, 0x63, 0xE3,
    0x13, 0x93, 0x53, 0xD3, 0x33, 0xB3, 0x73, 0xF3,
    0x0B, 0x8B, 0x4B, 0xCB, 0x2B, 0xAB, 0x6B, 0xEB,
    0x1B, 0x9B, 0x5B, 0xDB, 0x3B, 0xBB, 0x7B, 0xFB,
    0x07, 0x87, 0x47, 0xC7, 0x27, 0xA7, 0x67, 0xE7,
    0x17, 0x97, 0x57, 0xD7, 0x37, 0xB7, 0x77, 0xF7,
    0x0F, 0x8F, 0x4F, 0xCF, 0x2F, 0xAF, 0x6F, 0xEF,
    0x1F, 0x9F, 0x5F, 0xDF, 0x3F, 0xBF, 0x7F, 0xFF,
]

# ============================================================================
# ORIGINAL: TIFF IFD (Image File Directory) Parser
# Based on TIFF 6.0 specification
# Reads TIFF tags and extracts image data for CCITT Group 4 compressed images
# ============================================================================
def read_tiff_ifd(f, offset, endian):
    """Read one TIFF IFD and extract image info."""
    # ORIGINAL: Error handling for EOF
    f.seek(offset)
    num_entries_data = f.read(2)
    if len(num_entries_data) < 2:
        return None, 0
    num_entries = struct.unpack(endian + 'H', num_entries_data)[0]

    # ORIGINAL: Initialize tag variables
    width = height = compression = fillorder = photo = None
    strip_offsets = strip_bytes = []

    # ORIGINAL: Parse each IFD entry (based on TIFF spec)
    for i in range(num_entries):
        entry_offset = offset + 2 + i * 12
        f.seek(entry_offset)
        tag, field_type, count = struct.unpack(endian + 'HHI', f.read(8))
        value_offset = f.tell()

        # ORIGINAL: Read value based on TIFF field type
        if field_type == 3:  # SHORT (16-bit)
            if count == 1:
                value = struct.unpack(endian + 'H', f.read(2))[0]
            else:
                if count * 2 <= 4:
                    value = [struct.unpack(endian + 'H', f.read(2))[0] for _ in range(count)]
                else:
                    ptr = struct.unpack(endian + 'I', f.read(4))[0]
                    pos = f.tell()
                    f.seek(ptr)
                    value = [struct.unpack(endian + 'H', f.read(2))[0] for _ in range(count)]
                    f.seek(pos)
        elif field_type == 4:  # LONG (32-bit)
            if count == 1:
                value = struct.unpack(endian + 'I', f.read(4))[0]
            else:
                ptr = struct.unpack(endian + 'I', f.read(4))[0]
                pos = f.tell()
                f.seek(ptr)
                value = [struct.unpack(endian + 'I', f.read(4))[0] for _ in range(count)]
                f.seek(pos)
        else:
            continue

        # ORIGINAL: Map TIFF tags to variables (tag numbers from TIFF spec)
        if tag == 256:  # ImageWidth
            width = value
        elif tag == 257:  # ImageLength
            height = value
        elif tag == 259:  # Compression
            compression = value
        elif tag == 262:  # PhotometricInterpretation
            photo = value
        elif tag == 266:  # FillOrder (concept from img2pdf: check this tag)
            fillorder = value
        elif tag == 273:  # StripOffsets
            strip_offsets = value if isinstance(value, list) else [value]
        elif tag == 279:  # StripByteCounts
            strip_bytes = value if isinstance(value, list) else [value]

    # Read next IFD offset for multi-page TIFFs
    f.seek(offset + 2 + num_entries * 12)
    next_ifd = struct.unpack(endian + 'I', f.read(4))[0]

    # Only process CCITT Group 4 (compression == 4)
    if compression == 4 and width and height and strip_offsets and strip_bytes:  # Group 4
        # ORIGINAL: Validate dimensions for safety
        if width <= 0 or height <= 0 or width > 20000 or height > 20000:
            print(f"Warning: Invalid dimensions {width}x{height}, skipping page")
            return None, next_ifd

        # Read raw compressed data from strips
        data = b''
        try:
            for off, size in zip(strip_offsets, strip_bytes):
                if size > 0:
                    f.seek(off)
                    chunk = f.read(size)
                    # ORIGINAL: Validate complete read
                    if len(chunk) != size:
                        print(f"Warning: Could not read complete strip data")
                        return None, next_ifd
                    data += chunk
        except Exception as e:
            print(f"Error reading strip data: {e}")
            return None, next_ifd

        if not data:
            print("Warning: No image data found")
            return None, next_ifd

        # Handle FillOrder (bit reversal for LSB2MSB)
        # Concept from img2pdf: check fillorder and reverse bits if needed
        # Uses TIFFBitRevTable from libtiff
        if fillorder == 2:  # LSB2MSB
            data = bytearray(data)
            for i in range(len(data)):
                data[i] = TIFFBitRevTable[data[i]]
            data = bytes(data)

        # Track photometric interpretation for BlackIs1 parameter
        # Concept from img2pdf: invert BlackIs1 when photometric == WhiteIsZero
        inverted = (photo == 0)  # WhiteIsZero
        return {'width': width, 'height': height, 'data': data, 'inverted': inverted}, next_ifd

    return None, next_ifd

# ============================================================================
# ORIGINAL: Multi-page TIFF reader
# Iterates through TIFF IFD chain to read all pages
# ============================================================================
def read_tiff_file(tiff_path):
    """Read all pages from a TIFF file."""
    pages = []

    with open(tiff_path, 'rb') as f:
        # Read TIFF header (TIFF 6.0 spec)
        byte_order = f.read(2)
        endian = '<' if byte_order == b'II' else '>'
        magic = struct.unpack(endian + 'H', f.read(2))[0]
        if magic != 42:
            raise ValueError("Not a valid TIFF file")

        ifd_offset = struct.unpack(endian + 'I', f.read(4))[0]

        # Read all IFDs (following the IFD chain)
        while ifd_offset != 0:
            page, ifd_offset = read_tiff_ifd(f, ifd_offset, endian)
            if page:
                pages.append(page)

    return pages

# ============================================================================
# PDF/A-1B Creation
# IMPLEMENTATION: Original code, studied img2pdf's approach to CCITT embedding
# ORIGINAL: PDF/A metadata, CalGray colorspace, A4 scaling/centering
# ============================================================================
def create_pdf(pages, output_path):
    """Create PDF/A-1B compliant PDF from multiple CCITT images with A4 portrait pages."""
    # PDF header with binary marker
    pdf = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"

    # ORIGINAL: A4 portrait in points
    page_width_pt = 595
    page_height_pt = 842

    # Build objects array
    objects = []
    obj_num = 1

    # ORIGINAL: Reserve for PDF/A metadata
    metadata_obj_num = None
    output_intent_obj_num = None

    # ORIGINAL: CalGray color space (PDF/A compliant, device-independent)
    # Replaces DeviceGray to meet PDF/A requirements
    # D65 white point (standard for sRGB/daylight), Gamma 1.0 for neutral rendering
    calgray_colorspace = "[/CalGray << /WhitePoint [0.9505 1.0000 1.0890] /Gamma 1.0 >>]"

    # Reserve object number for Pages object (needed for /Parent references)
    # Each page needs 3 objects: image XObject, content stream, page object
    pages_obj_num = obj_num + (len(pages) * 3)

    # Create image and content objects for each page
    page_obj_nums = []
    for i, page in enumerate(pages):
        # ====================================================================
        # Image XObject
        # ====================================================================
        img_obj_num = obj_num
        obj_num += 1

        data_length = len(page['data'])

        # Image XObject dictionary
        # ColorSpace: ORIGINAL (CalGray instead of DeviceGray for PDF/A)
        # BlackIs1 logic: concept from img2pdf (inverted when photometric == 0)
        # DecodeParms format: concept from img2pdf (K=-1, Columns, Rows)
        # Decode array: ORIGINAL (explicit black/white mapping for neutral rendering)
        img_dict = (
            f"<< /Type /XObject "
            f"/Subtype /Image "
            f"/Width {page['width']} "
            f"/Height {page['height']} "
            f"/ColorSpace {calgray_colorspace} "  # ORIGINAL: CalGray for PDF/A
            f"/BitsPerComponent 1 "
            f"/Filter /CCITTFaxDecode "
            f"/DecodeParms << /K -1 /BlackIs1 {'false' if page['inverted'] else 'true'} "
            f"/Columns {page['width']} /Rows {page['height']} >> "
            f"/Decode [0 1] "  # ORIGINAL: Explicit sample 0→black (0.0), sample 1→white (1.0)
            f"/Length {data_length} >>"
        ).encode()

        # Embed raw CCITT data without re-encoding
        img_obj = img_dict + b"\nstream\n" + page['data'] + b"\nendstream"
        objects.append(img_obj)

        # ====================================================================
        # Content Stream - ORIGINAL: A4 scaling and centering logic
        # ====================================================================
        content_obj_num = obj_num
        obj_num += 1

        # ORIGINAL: Calculate aspect ratios and scale to fit A4
        img_aspect = page['width'] / page['height']
        page_aspect = page_width_pt / page_height_pt

        if img_aspect > page_aspect:
            # Image is wider - fit to width
            scale = page_width_pt / page['width']
        else:
            # Image is taller - fit to height
            scale = page_height_pt / page['height']

        scaled_width = page['width'] * scale
        scaled_height = page['height'] * scale

        # ORIGINAL: Center image on A4 page
        x_offset = (page_width_pt - scaled_width) / 2
        y_offset = (page_height_pt - scaled_height) / 2

        # Content stream with transformation matrix
        # ORIGINAL: Transformation matrix values for A4 centering
        content_stream = (
            f"q\n{scaled_width:.4f} 0 0 {scaled_height:.4f} {x_offset:.4f} {y_offset:.4f} cm\n/Im{i} Do\nQ\n"
        ).encode()

        content_obj = (
            f"<< /Length {len(content_stream)} >>".encode() +
            b"\nstream\n" + content_stream + b"\nendstream"
        )
        objects.append(content_obj)

        # ====================================================================
        # Page object
        # ORIGINAL: A4 MediaBox instead of image dimensions
        # ====================================================================
        page_obj_num = obj_num
        obj_num += 1
        page_obj_nums.append(page_obj_num)

        page_obj = (
            f"<< /Type /Page /Parent {pages_obj_num} 0 R "
            f"/MediaBox [0 0 {page_width_pt} {page_height_pt}] "  # ORIGINAL: Fixed A4 size
            f"/Resources << /XObject << /Im{i} {img_obj_num} 0 R >> >> "
            f"/Contents {content_obj_num} 0 R >>"
        ).encode()
        objects.append(page_obj)

    # ========================================================================
    # Pages object (object number was reserved earlier)
    # ========================================================================
    # pages_obj_num already set before the loop
    obj_num += 1

    kids = ' '.join([f"{n} 0 R" for n in page_obj_nums])
    pages_obj = (
        f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>"
    ).encode()
    objects.append(pages_obj)

    # ========================================================================
    # XMP Metadata stream - ORIGINAL: PDF/A-1B requirement
    # ========================================================================
    metadata_obj_num = obj_num
    obj_num += 1

    import datetime
    now = datetime.datetime.now(datetime.timezone.utc)
    timestamp = now.strftime('%Y-%m-%dT%H:%M:%S+00:00')

    # ORIGINAL: Full XMP metadata for PDF/A-1B compliance
    xmp_metadata = f'''<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:format>application/pdf</dc:format>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">
      <pdfaid:part>1</pdfaid:part>
      <pdfaid:conformance>B</pdfaid:conformance>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
      <xmp:CreateDate>{timestamp}</xmp:CreateDate>
      <xmp:ModifyDate>{timestamp}</xmp:ModifyDate>
      <xmp:MetadataDate>{timestamp}</xmp:MetadataDate>
      <xmp:CreatorTool>tiff2pdf_img2pdf.py (PDF to CCITT Converter)</xmp:CreatorTool>
    </rdf:Description>
    <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
      <pdf:Producer>tiff2pdf_img2pdf.py (PDF to CCITT Converter)</pdf:Producer>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>'''.encode('utf-8')

    metadata_obj = (
        f"<< /Type /Metadata /Subtype /XML /Length {len(xmp_metadata)} >>".encode() +
        b"\nstream\n" + xmp_metadata + b"\nendstream"
    )
    objects.append(metadata_obj)

    # ========================================================================
    # OutputIntent - ORIGINAL: PDF/A-1B requirement
    # Declares the intended output condition (grayscale with gamma 2.2)
    # ========================================================================
    output_intent_obj_num = obj_num
    obj_num += 1

    output_intent_obj = (
        f"<< /Type /OutputIntent "
        f"/S /GTS_PDFA1 "
        f"/OutputConditionIdentifier (Gray Gamma 2.2) "
        f"/Info (Grayscale with Gamma 2.2) >>"
    ).encode()
    objects.append(output_intent_obj)

    # ========================================================================
    # Catalog
    # ORIGINAL: Added Metadata, OutputIntents, MarkInfo, ViewerPreferences for PDF/A
    # ========================================================================
    catalog_obj_num = obj_num
    obj_num += 1

    catalog_obj = (
        f"<< /Type /Catalog /Pages {pages_obj_num} 0 R "
        f"/Metadata {metadata_obj_num} 0 R "  # ORIGINAL: PDF/A requirement
        f"/OutputIntents [{output_intent_obj_num} 0 R] "  # ORIGINAL: PDF/A requirement
        f"/MarkInfo << /Marked true >> "  # ORIGINAL: PDF/A requirement
        f"/ViewerPreferences << /DisplayDocTitle true >> >>"  # ORIGINAL: PDF/A best practice
    ).encode()
    objects.append(catalog_obj)

    # ========================================================================
    # Write PDF structure
    # ========================================================================
    # Write objects and build xref table
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"

    # Write xref table
    xref_offset = len(pdf)
    pdf += b"xref\n"
    pdf += f"0 {len(objects) + 1}\n".encode()
    pdf += b"0000000000 65535 f \n"
    for offset in offsets:
        pdf += f"{offset:010d} 00000 n \n".encode()

    # ========================================================================
    # Trailer
    # ORIGINAL: Added ID array for PDF/A compliance
    # ========================================================================
    import hashlib
    import time

    # ORIGINAL: Generate unique file ID (PDF/A requirement)
    id_source = f"{output_path}{time.time()}{len(pages)}".encode()
    file_id = hashlib.md5(id_source).hexdigest().upper()

    pdf += b"trailer\n"
    pdf += (
        f"<< /Size {len(objects) + 1} "
        f"/Root {catalog_obj_num} 0 R "
        f"/ID [<{file_id}> <{file_id}>] >>\n"  # ORIGINAL ID array for PDF/A
    ).encode()
    pdf += b"startxref\n"
    pdf += f"{xref_offset}\n".encode()
    pdf += b"%%EOF\n"

    with open(output_path, 'wb') as f:
        f.write(pdf)

# ============================================================================
# ORIGINAL: Command-line interface
# Multi-file support for batch processing
# ============================================================================
if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: tiff2pdf_img2pdf.py input1.tif [input2.tif ...] output.pdf")
        sys.exit(1)

    input_files = sys.argv[1:-1]
    output_file = sys.argv[-1]

    all_pages = []
    for tiff_path in input_files:
        if not os.path.exists(tiff_path):
            print(f"Error: {tiff_path} not found")
            sys.exit(1)

        try:
            pages = read_tiff_file(tiff_path)
            if not pages:
                print(f"Warning: No CCITT Group 4 pages in {tiff_path}")
            else:
                all_pages.extend(pages)
        except Exception as e:
            print(f"Error reading {tiff_path}: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)

    if not all_pages:
        print("Error: No valid pages found")
        sys.exit(1)

    try:
        create_pdf(all_pages, output_file)
        print(f"Successfully created {output_file} with {len(all_pages)} page(s)")
    except Exception as e:
        print(f"Error creating PDF: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
